### ISSUE TITLE
It should be possible to translate the client

### ISSUE THREAD

**Issue by schoen** [letsencrypt/letsencrypt#2261] opened 2016-01-22 18:14 UTC
Right now the client uses hard-coded English strings (and in some places may substitute individual words into the middle of a sentence by string substitution). So if someone were to contribute a translation, or if we were to solicit someone, we wouldn't have a way to integrate the translation.

**Comment by kuba** [comment] 2016-01-24 07:01
Dupe of #115

**Closed by kuba** 2016-01-24 07:01 UTC
