### ISSUE TITLE
request via --csr fails

### ISSUE THREAD

**Issue by gdkags** [letsencrypt/letsencrypt#1647] opened 2015-12-01 17:18 UTC
I might have done something wrong, but I could not get it to work.
Might be all my fault, tho.
Python fails somewhere while trying to parse the SANs, could not get my head around the openssl python lib.

Distro: arch
LE-Version: 0.0.0.dev20151123-1

At least you should be able to reproduce with those two things:

LE was started via:
```
letsencrypt certonly --authenticator standalone --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview --csr 20151201-mk2.0ds.de.csr --cert-path le-certs/
```

the csr in question is here.
```
-----BEGIN CERTIFICATE REQUEST-----
MIIE9jCCAuICAQAwWzELMAkGA1UEBhMCREUxCzAJBgNVBAgMAkJXMQwwCgYDVQQH
DANVbG0xIDAeBgNVBAoMFzBkcy5kZSBwcml2YXRlIGhvcnN0aW5nMQ8wDQYDVQQD
DAYwZHMuZGUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDb8KwJNgBR
xmZEMOvte6CSdn9CNa/JjRJqsCCuoFZNfkAsVchDv1Il8/PbjU73+zr3L1HAGj1E
YvSM3o5ww9Klg2tA1sBwGgrP9lNrVtsGS+43zhUI/LyDEh/hNth2bC5DNWBxZB8x
vyPRBklPE5WiWoVEyqW5sGIKMl9PVk6/nsdbIyHmnz0TcoiDCN7Uea5R6FR2FQLt
Sa+vcs/qk+eCnDVxqbaNEx5gnnJXWAUAfSBFGo4jF32HOgPD88NXDz6PkmkaDIpd
QEc/IzHYN64PhVdOVLd9w0tSrYS8dMOg55ViXDetFq+dss1SdjRGSg87bJnHk4ij
HUK0XLcMHNOuXZEcr5licbsvvuWUkSnk+MNqizV34UV7WSU3kWBx4u/WFZPUKS4B
igqetz4Cj4pjoGE9fS/1wnuBe6mVCIxxP+wa6+0h4yeZ2E6oy1NAl1X+YfvdKQ7E
hL3Tir1100/LZt6mH0Rn+3SmNGnvXJa6mw/Ww83Y/kuHRCuEZrxKy8hQc+1PLy7+
IcTfT8nn6GydKqKe7ZwonbfoqURW0aluq31XD9GEMDNdUVz1/ayNZU5S+4UdJOkU
D04JwLPD+Qw7Iy5AWpt0cDJO0OHEOoaASbT/XaXFiLOCt0EHTVqqn8Ke6DrLkVMF
77kojC3MyggjfKb1Zg1DmlpxgCtzu8EsTwIDAQABoFowWAYJKoZIhvcNAQkOMUsw
STAJBgNVHRMEAjAAMAsGA1UdDwQEAwIF4DAvBgNVHREEKDAmggptazIuMGRzLmRl
ggtkb2t1LjBkcy5kZYILYmxvZy4wZHMuZGUwCQYFKw4DAg8FAAOCAgEAODT+a7gT
KUzK8xWqy17rAMFP3jddfZnTas2P+Z2ajyWNTVUfaGmEYDTxW0zMVLDA6ep8pG44
5fVk7xhkR+uBja6jKFYEi5haTXlQgh9vDyWZeVM37e1zwMS4iIYRY5xE/MpTlbil
F20JqJpqVaq7+7ltAYVgodePvOX/MBCOJL01aTUtiGWGjnOz4Aif+NREoLyjcw5M
zKzNLK404a9vepIpxRvqBKB10x+xAGyC+i/5J5iNlvSv96B47QBN+9DDFem7mUG4
nwAFWBxa+lRMvJINHVOnZ5+KYiPY7WqimSZBQtna+6FGGWWOYS7OJxmLe1TiP8+2
kr+CMBtagQc0kvArpANpsz3V/cM3XzGYNLJsmzfixNjy8Z7mrSLIakZMcHpF6hFQ
1s13u67frRPPAjZ5QdESVSjbyAEdaNcYKaAZwJjOwN++XYp4hQ7qxADZQJzeB7ak
xvDwbbqKVZmmRHaFt5QFX3rz2npzWn62Q6le4MjyJ4HuwOM0c06TDfLZ/XNuZWDE
ojE/DHx1l3090iKVNd8oAG59mI1VjXLG0nRMPNjtCnrYFNRQXIEJnVR9DELw5bHg
BJJa2OKN3a25gHRRjnOJpsXr9bTjg7PL57vafx/QMiF6mwrZQGJhK+lIcq21s1F0
dmj7lq2s8hT0BUpi3USeU0TQwSMJi/0GUkU=
-----END CERTIFICATE REQUEST-----
```
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 225, in _get_sans_from_cert_or_req
    cert_or_req = load_func(typ, cert_or_req_str)
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 2380, in load_certificate_request
    _raise_current_error()
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
2015-12-01 15:13:21,018:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.0.0.dev20151123', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/site-packages/letsencrypt/cli.py", line 1206, in main
    return args.func(args, config, plugins)
  File "/usr/lib/python2.7/site-packages/letsencrypt/cli.py", line 494, in obtain_cert
    file=args.csr[0], data=args.csr[1], form="der"))
  File "/usr/lib/python2.7/site-packages/letsencrypt/client.py", line 245, in obtain_certificate_from_csr
    csr.data, OpenSSL.crypto.FILETYPE_ASN1), csr)
  File "/usr/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 258, in get_sans_from_csr
    csr, OpenSSL.crypto.load_certificate_request, typ)
  File "/usr/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 225, in _get_sans_from_cert_or_req
    cert_or_req = load_func(typ, cert_or_req_str)
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 2380, in load_certificate_request
    _raise_current_error()
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
```

If you need more information, I'll gladly try to help.

Thank you for being awesome!

**Comment by pde** [comment] 2015-12-01 19:51
Presently --csr only supports DER formatted certificates, and not PEM certs.  Feel free to send us a pull request to support both!

**Comment by pde** [comment] 2015-12-01 19:51
Duplicate of #1082.

**Closed by pde** 2015-12-01 19:51 UTC
