### ISSUE TITLE
Error parsing owncloud.conf

### ISSUE THREAD

**Issue by jojom4n** [letsencrypt/letsencrypt#1734] opened 2015-12-04 11:46 UTC
When executing 

    letsencrypt --apache

and after accepting the EULA, I receive the following:

    The apache plugin is not working; there may be problems with your existing configuration.
    The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/owncloud.conf', u'Syntax error'),)

Here's my owncloud.conf:
```   
<VirtualHost *:80>
  ServerName localhost
  DocumentRoot /var/www/owncloud/
  ServerAdmin webmaster@localhost

  <Directory /var/www/owncloud>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
    SetEnv MOD_X_SENDFILE_ENABLED 1
    XSendFile On
    XSendFilePath /tmp/oc-noclean
  </Directory>

  ErrorLog /var/log/apache2/error_$domain.log

  SetOutputFilter DEFLATE
  SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|ico|png)$ \ no-gzip dont-vary
  SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|bz2|sit|rar)$ \no-gzip dont-vary
  SetEnvIfNoCase Request_URI \.pdf$ no-gzip dont-vary

  BrowserMatch ^Mozilla/4 gzip-only-text/html
  BrowserMatch ^Mozilla/4\.0[678] no-gzip
  BrowserMatch \bMSIE !no-gzip !gzip-only-text/html

</VirtualHost>
```   
I'm on Debian testing, libaugeas0 = 1.2.0-0.2-2 and apache2 = 2.4.17-3. Let's Encrypt version, on the other hand, is  0.0.0.dev20151123 (I installed it from experimental branch).

**Comment by Petertjuh360** [comment] 2015-12-04 16:12
Can you also post the owncloud.conf before running the command?

**Comment by jojom4n** [comment] 2015-12-04 17:03
I checked from a backup of the last week and the owncloud.conf, before running the command, is exactly the same as the one I posted before. The command didn't touch it (that makes some sense, since it couldn't parse and work on it, I think).

**Comment by pde** [comment] 2015-12-04 18:18
This is a duplicate of #1531.

**Closed by pde** 2015-12-04 18:18 UTC
