### ISSUE TITLE
Generate separate certificates for discovered domains

### ISSUE THREAD

**Issue by arthurlutz** [letsencrypt/letsencrypt#2006] opened 2015-12-23 20:55 UTC
I've tried using the discovery of domains with letsencrypt and it works great! One small bug in my opinion which forces me to go through all my sites is that the generated certificate is the same for all domains and thus when one connects to https://a.example.org  they get to know that https://supersecret.example.org also exists. 

Is there an options to get separate certificates for each domain found in the apache config ? If not, could we get one ? 

Grouping ServerName and ServerAlias could be a good thing in this use case.

**Comment by bmw** [comment] 2015-12-23 21:22
Currently the only way to do this is to run the client once for each domain, only requesting a certificate for the single domain.

**Comment by arthurlutz** [comment] 2015-12-23 21:51
@bmw yes, that's what am doing right now, and will probably do via automation software salt, but would such an option be useful for the community ?

**Comment by bmw** [comment] 2015-12-23 22:11
I think so. I can't imagine you're the only one who would find this useful.

There was discussion of this issue on a related PR/issue a long time ago but looking quickly, I seem unable to find it.

**Comment by pde** [comment] 2015-12-25 21:35
This is a duplicate of #369.

**Closed by pde** 2015-12-25 21:35 UTC
Labels: enhancement

**Comment by arthurlutz** [comment] 2016-01-14 15:03
I've learned about the Certificate Transparency part of letsencrypt. To protect user's privacy from leaking https://supersecret.example.org to a public website, maybe there could be a warning when launching the tool and creating certificates. In particular when creating certificates for multiple domains.
