### ISSUE TITLE
get cert by exist csr failed

### ISSUE THREAD

**Issue by lainredsonic** [letsencrypt/letsencrypt#1891] opened 2015-12-14 10:11 UTC
clear installed opensuse 13.2

./letsencrypt-auto certonly -d a.xxx.cf -d xxx.cf       simply and everything is ok

openssl req -nodes -newkey rsa:2048 -sha256 -outform der -keyout priv.key -out cert.csr -subj '/'  \
-reqexts SAN \
-config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:a.xxx.cf,DNS:xxx.cf"))

./letsencrypt-auto certonly --csr cert.csr 

get error:
An unexpected error occurred:
UnexpectedUpdate: AuthorizationResource(body=Authorization(status=Status(pending), challenges=(ChallengeBody(chall=HTTP01(token='\x80\x94\xb3\x1c\xfc\xa9\xe8Z\xd2\xd7\x846I_\x83\x82\xef\xed\xec\x97\xb8Z#`;\xf0-\x8e\xa9\x93\x91`'), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/nAzrnEBXvFcslfKfbXMWsxAfkJAIW8h4CYrntBJcJzw/1809347', error=None), ChallengeBody(chall=TLSSNI01(token='\xaf\x7f7\xa2\x87\xbe\xdd\xc7\x87\x07\xaa\x19\xa3<\xc8"\xd4\x7f\x05\xd4\xe3\x85\xef\x0e\xf1\xe2\xd1\xec\n\x13[R'), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/nAzrnEBXvFcslfKfbXMWsxAfkJAIW8h4CYrntBJcJzw/1809348', error=None)), identifier=Identifier(typ=IdentifierType(dns), value=u'a.xxx.cf'), expires=datetime.datetime(2015, 12, 21, 10, 5, 59, 298352, tzinfo=<UTC>), combinations=((1,), (0,))), new_cert_uri='https://acme-v01.api.letsencrypt.org/acme/new-cert', uri='https://acme-v01.api.letsencrypt.org/acme/authz/nAzrnEBXvFcslfKfbXMWsxAfkJAIW8h4CYrntBJcJzw')
Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by jespertheend** [comment] 2015-12-19 19:57
Same problem here,
possibly a duplicate of #1712

**Comment by lainredsonic** [comment] 2015-12-29 16:23
I resolve it by myself , the root cause is X509v3 Subject Alternative Name is case-sensitive, although dns not. I think #1712 is same reason and banned code is 

if authzr.body.identifier != identifier:
  raise errors.UnexpectedUpdate(authzr)

**Closed** 2015-12-29 16:24 UTC
