### ISSUE TITLE
apache mode fails on ipv6 listen directive

### ISSUE THREAD

**Issue by dc7kr** [letsencrypt/letsencrypt#2231] opened 2016-01-19 13:08 UTC
Commandline used:
```bash
./letsencrypt-auto --apache -d somedomain.com
```

The client (master branch at git commit 91b9d5f30e783259bf12742e53910918a959ac7b) has issues parsing the following ports.conf that contains an ipv6 address:
```apache
Listen 80

<IfModule ssl_module>
  Listen 192.168.1.1:443
  Listen [2a01:aaa:bbb:ccc::1]:443
</IfModule>

<IfModule mod_gnutls.c>
  Listen 192.168.1.1:443
  Listen [2a01:aaa:bbb:ccc::1]:443
</IfModule>
```
The client fails with this error message: 
```
MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 2 of /etc/apache2/le_tls_sni_01_cert_challenge.conf:
The address or port is invalid
```
I grabbed the generated /etc/apache2/le_tls_sni_01_cert_challenge.conf file and found the following (invalid) contents: 
```apache
<VirtualHost [2a01:443>
    ServerName **hexstring**.**hexstring**.acme.invalid
    UseCanonicalName on
    SSLStrictSNIVHostCheck on

    LimitRequestBody 1048576

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /var/lib/letsencrypt/*alphastring*-*alphastring*.crt
    SSLCertificateKeyFile /var/lib/letsencrypt/alphastring-alphastring.pem

    DocumentRoot /var/lib/letsencrypt/tls_sni_01_page/
</VirtualHost>
```

The IPv6 Address / Port combination [2a01:....]:443 is truncated - looks like a splt at ":" and then the first and last part are used which is correct for IPv4 but wrong for IPV6 addresses.

**Comment by bmw** [comment] 2016-01-19 22:45
Dupe of #1143.

**Closed by bmw** 2016-01-19 22:45 UTC
