### ISSUE TITLE
Client should strongly encourage use of an email address

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#414] opened 2015-05-13 23:26 UTC
If the CA has many (/any) users with no email on file, it's going to cause a lot of hassles. We're still deciding if we want it to be official policy that everyone has to provide an email, but in the meantime we can work on the client side of this. Proposal: The interactive version of the client should ask for an email, and not proceed without one, unless it was invoked with a --allow-unsafe-registration. The help documentation for --allow-unsafe-registration would say:

"Specifying this flag enables registering an account with no email address. This is strongly discouraged, because in the event of key loss or account compromise you will irrevocably lose access to your account. You will also be unable to receive notice about impending expiration of revocation of your certificates. Updates to the Subscriber Agreement will still affect you, and the CA will make a best-effort attempt to notify you about them based on information about the affected domains, such as WHOIS data and common administrative addresses."

**Comment by kuba** [comment] 2015-05-22 13:08
duplicate of #410?

**Comment by jsha** [comment] 2015-05-22 16:52
One idea on this: We want it to be more convenient to provide an email than to not provide one. I suspect the most common unintended no-email case would be copy-pasted command lines.

Proposal: By default, the UI and command line require an email address. To register with no email address, you must pass the client an --allow-unsafe-registration and use the UI (not the command line). The UI would prompt you if you leave the email address empty with a description of all the ways in which it's risky (no expiration notices, no account recovery (which can mean inability to issue future certs), and no notice of subscriber agreement changes).

**Comment by miquelruiz** [comment] 2015-10-24 12:27
FYI I'm working on this. I hope I'll have a PR ready this weekend.

**Comment by bmw** [comment] 2015-10-24 16:34
Fantastic! We appreciate the help @miquelruiz. Welcome to the project.

**Comment by jsha** [comment] 2015-10-24 17:28
Thanks @miquelruiz! Note: in my original post, I included language "and the CA will make a best-effort attempt to notify you about them based on information about the affected domains, such as WHOIS data and common administrative addresses." That's no longer true: for people who don't provide email addresses, updates to the Subscriber agreement are effective N days after posting an update to the web site.

**Comment by miquelruiz** [comment] 2015-10-24 21:59
Is there a definitive value for "N days" to be included in the help?

**Comment by miquelruiz** [comment] 2015-10-24 22:43
Pull request attached. Please feel free to suggest any improvement :)

**Closed** 2015-11-21 03:16 UTC
Labels: easy-fix, Good Volunteer Task, has pr, ui / ux
