### ISSUE TITLE
Failed building wheel for cryptography

### ISSUE THREAD

**Issue by viveleroi** [letsencrypt/letsencrypt#1753] opened 2015-12-04 20:25 UTC
Seems to be unrelated to #1147.

On CentOS, python 2.7.6. I have both openssl and openssl-devel packages installed.

`letsencrypt-auto certonly --standalone -d mydomain.com  --verbose`

```
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
build/temp.linux-x86_64-2.7/_openssl.c:1759: warning: function declaration isn’t a prototype
gcc: Internal error: Killed (program cc1)
Please submit a full bug report.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
error: command 'gcc' failed with exit status 1

Command "/root/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-NCLZpt/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-HfCWw_-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-NCLZpt/cryptography
```

**Comment by heejongahn** [comment] 2015-12-05 08:22
Similar issue here.
I'm using python 2.7.9 virtual environment at Ubuntu 14.04 LTS.
Installed letsencrypt with git clone.

When I try `./letsencrypt-auto --help`, error message below shows up,

```
Failed building wheel for cryptography
Command "/home/ubuntu/letsencrypt/venv/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-XBz7Ej/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-uNw97W-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/letsencrypt/venv/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-XBz7Ej/cryptography
```

tried certonly option too, didn't make any difference.

**Comment by coeusite** [comment] 2015-12-09 02:28
Similar issue here on my VPS (OpenVZ (Ramnode) + Debian 8.0).

Error log shows that: ``` x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1) ```

```
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_padding.c'
    creating build/temp.linux-x86_64-2.7
    generating cffi module 'build/temp.linux-x86_64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    
    ----------------------------------------
Command "/root/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-brNUbR/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hha7xI-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-brNUbR/cryptography

```

**Comment by sjohannes** [comment] 2015-12-09 03:19
This is a duplicate of #1081.

**Closed** 2015-12-11 00:33 UTC
