### ISSUE TITLE
Webroot test does not remove .well-known

### ISSUE THREAD

**Issue by othatbrian** [letsencrypt/letsencrypt#2854] opened 2016-04-16 04:46 UTC
I created certificates for several of my domains and noticed that letsencrypt left behind an empty `.well-known` directory in my webroot. This happens because it uses `os.makedirs` to create `{root_path}/URI_ROOT_PATH`, with `URI_ROOT_PATH` being `.well-known/acme-challenges`. When it cleans up, it removes the single directory `root_path/URI_ROOT_PATH`, but it doesn't remove *each level* of the URI_ROOT_PATH it created.

I attempted a patch here which "steps up" each level of URI_ROOT_PATH and attempts to delete them: https://github.com/othatbrian/letsencrypt/commit/74dd1fc7d502d1a1de3881e7be0bd13df9b3c86f
but I haven't set up a test environment to attempt to test that particular fix.

**Comment by textshell** [comment] 2016-04-17 16:48
I don’t think unconditionally removing the .well-known/acme-challenge is a good idea. I personally would think just to leave it around. But if removing is to be done, then it should only remove the parts it actually created.

For setups with an alias into a letsencrypt directory removing the directories would be the wrong thing to do, because that would leave the alias point to a non existing directory.

    Alias "/.well-known/acme-challenge" "/srv/letsencrypt/example.com/.well-known/acme-challenge"

**Comment by othatbrian** [comment] 2016-04-17 21:18
> I don’t think unconditionally removing the .well-known/acme-challenge is a good idea.

I would not say this is "unconditionally removing" a directory. Because it uses "os.rmdir", it will only be removed if the directory is empty; generally speaking, [almost] any empty directory can be safely removed.

> But if removing is to be done, then it should only remove the parts it actually created.

That's my issue: in my case (and I suspect in many others), letsencrypt creates this directory (`.well-known` as well as `.well-known/acme-challenge`), but does not remove it.

> For setups with an alias into a letsencrypt directory removing the directories would be the wrong thing to do, because that would leave the alias point to a non existing directory.

> ```Alias "/.well-known/acme-challenge" "/srv/letsencrypt/example.com/.well-known/acme-challenge"```

I don't agree here, either, as the `acme-challenge` directory is already being removed, so you'd be left with an alias to a nonexistent directory anyway.

My point is basically as you mentioned: if letsencrypt creates a directory in my docroot which is no longer needed, it should remove it. It does _attempt_ to remove directories, but my issue is that it does not in fact remove all the directories it creates. Maybe keeping a "stack" of directories it creates which are to be removed later would be a better solution?

**Comment by textshell** [comment] 2016-04-17 21:52
Yes. I believe leaving the directories as they were before letsencrypt/certbot ran would be the best solution. I guess implementation complexity for 2 directories is still manageable. `_validate_webroot` ensures that the webroot itself always exists.

Yes, for my use-case i had to add a ".keep" file when i realized that certbot deleted my directories. Which doesn't feel like it should be need.

**Comment by bmw** [comment] 2016-04-18 21:23
While perhaps this title is a little more direct, I believe this issue is a duplicate of #1003. I suggested the same approach [here](https://github.com/letsencrypt/letsencrypt/issues/1003#issuecomment-201538065) of deleting the directory iff we created it, but haven't been able to get around to writing the PR.

**Closed by bmw** 2016-04-18 21:23 UTC
