### ISSUE TITLE
Error parsing apache configuration with IfModule and RewriteRule

### ISSUE THREAD

**Issue by fhimpe** [letsencrypt/letsencrypt#1844] opened 2015-12-09 15:50 UTC
```
# ./letsencrypt-auto --apache --server https://acme-v01.api.letsencrypt.org/directory
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --apache --server https://acme-v01.api.letsencrypt.org/directory
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/conf-enabled/block-bad-ua.conf', u'Syntax error'),)

# cat /etc/apache2/conf-enabled/block-bad-ua.conf
<IfModule mod_rewrite.c>
	RewriteCond %{HTTP_HOST} !^(127\.0\.0\.0|localhost|::1)
	RewriteCond %{HTTP_USER_AGENT} ^Xenu\ Link\ Sleuth
	RewriteRule ^.* - [F,L]
</IfModule>
```

**Comment by bmw** [comment] 2015-12-11 00:52
Dupe of #1620

**Closed by bmw** 2015-12-11 00:52 UTC
