### ISSUE TITLE
Listening to any IP address in /etc/apache2/ports.conf results in failure

### ISSUE THREAD

**Issue by rubin110** [letsencrypt/letsencrypt#1994] opened 2015-12-23 03:33 UTC
```
# ./letsencrypt-auto --apache --text -vvvvv
-vvvvv
Updating letsencrypt and virtual environment dependencies...

...

What would you like to do?
-------------------------------------------------------------------------------
1: Attempt to reinstall this existing certificate 
2: Renew & replace the cert (limit ~5 per 7 days) 
3: Cancel this operation and do nothing
-------------------------------------------------------------------------------
Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 1
2015-12-23 03:05:45,459:INFO:letsencrypt_apache.configurator:Deploying Certificate to VirtualHost /etc/apache2/sites-available/someobscuredomain.net-le-ssl.conf
2015-12-23 03:05:45,461:DEBUG:letsencrypt_apache.configurator:Apache version is 2.4.10
2015-12-23 03:05:45,743:ERROR:letsencrypt.le_util:Error while running apache2ctl -k graceful.
httpd not running, trying to start
Action '-k graceful' failed.
The Apache error log may have more information.

(98)Address already in use: AH00072: make_sock: could not bind to address 127.0.0.1:443
no listening sockets available, shutting down
AH00015: Unable to open logs

2015-12-23 03:05:45,751:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 385, in deploy_certificate
    self.installer.restart()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1222, in restart
    self._reload()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1233, in _reload
    raise errors.MisconfigurationError(str(err))  
MisconfigurationError: Error while running apache2ctl -k graceful.
httpd not running, trying to start
Action '-k graceful' failed.
The Apache error log may have more information.   

(98)Address already in use: AH00072: make_sock: could not bind to address 127.0.0.1:443
no listening sockets available, shutting down
AH00015: Unable to open logs


2015-12-23 03:05:45,755:DEBUG:letsencrypt.error_handler:Calling registered functions
2015-12-23 03:05:45,755:CRITICAL:letsencrypt.client:Rolling back to previous server configuration...
2015-12-23 03:05:46,016:INFO:letsencrypt.reporter:Reporting to user: We were unable to install your certificate, however, we successfully restored your server to its prior configuration.
2015-12-23 03:05:46,020:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 561, in run
    lineage.chain, lineage.fullchain)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 385, in deploy_certificate
    self.installer.restart()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1222, in restart
    self._reload()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1233, in _reload
    raise errors.MisconfigurationError(str(err))  
MisconfigurationError: Error while running apache2ctl -k graceful.
httpd not running, trying to start
Action '-k graceful' failed.
The Apache error log may have more information.   

(98)Address already in use: AH00072: make_sock: could not bind to address 127.0.0.1:443
no listening sockets available, shutting down
AH00015: Unable to open logs


Error while running apache2ctl -k graceful.
httpd not running, trying to start
Action '-k graceful' failed.
The Apache error log may have more information.   

(98)Address already in use: AH00072: make_sock: could not bind to address 127.0.0.1:443
no listening sockets available, shutting down
AH00015: Unable to open logs


IMPORTANT NOTES:
 - We were unable to install your certificate, however, we
   successfully restored your server to its prior configuration.
```

When I went through and commented the following line out of /etc/apache2/ports.conf the problem went away.

```
Listen 127.0.0.1:8088
```

The line had nothing to do with 443 or SSL.

Notes, I was sitting next to Noah when this happened. It was like magic.

**Comment by rubin110** [comment] 2015-12-23 03:34
Noah says this is related to #1739.

**Comment by watercrossing** [comment] 2015-12-23 09:27
I can't reproduce this. Do you have any other `Listen` statements in your apache configuration files?

**Comment by rubin110** [comment] 2015-12-23 17:07
```
$ grep -R Listen *
ports.conf:Listen 80
ports.conf:#Listen 127.0.0.1:8088
ports.conf:     Listen 443
ports.conf:#    Listen 443
```

```
$ cat /etc/apache2/ports.conf
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

#NameVirtualHost *:80
Listen 80
#Listen 127.0.0.1:8088

<IfModule ssl_module>
        Listen 443
</IfModule>

#<IfModule mod_gnutls.c>
#       Listen 443
#</IfModule>

```

Again the only change made to ports.conf was to comment out Listen 127.0.0.1:8088, then letsencrypt started working.

**Comment by pde** [comment] 2015-12-26 21:44
@watercrossing would you be interested in taking a look at this?  It seems like it might be a bug in #1831?

**Comment by watercrossing** [comment] 2015-12-26 21:48
I will do, but I am on holidays this week. It will have to wait until the
new year.

**Comment by pde** [comment] 2016-01-04 16:15
@watercrossing ok great!  We're planning to try to freeze 0.2.0 at the end of this week, so if there's a simple fix for this let's try to land it by then.

**Comment by SwartzCr** [comment] 2016-01-05 15:36
My guess is that apache 2.2 doesn't accept the https addendum to the Listen directive:
apache 2.2: https://httpd.apache.org/docs/2.2/en/bind.html
apache 2.4: https://httpd.apache.org/docs/2.4/bind.html
so the server fails to start when it tries to parse the newly made conf file with
`Listen 127.0.0.1:8088 https`
So maybe we should ignore all non-443 listen directives on apache 2.2 (at least for the auth test)

**Comment by SwartzCr** [comment] 2016-01-05 15:46
`prepare_server_https` in configurator.py is only called in two places, once in configurator in `deploy_cert` and once in the tls_sni_01 `perform` test
My recommendation would be to check apache version in `prepare_server_https` and if temp=True then to ignore and if temp=False then to fail on version `(2, 2)`

**Comment by watercrossing** [comment] 2016-01-05 15:49
Nah, this is not the issue. I forgot an edge case in my previous pull request - `prepare_server_https` adds an additional `Listen 127.0.0.1:443` to the config, even though we are already listening to `443` on all interfaces. A new pull request that should fix this is in the pipeline!

**Comment by watercrossing** [comment] 2016-01-05 15:51
TBH `def prepare_server_https(self, port, temp=False):` should really be able to specify a listening interface, rather than just a port...

**Comment by SwartzCr** [comment] 2016-01-05 15:53
okay, please link the PR here when it's up and I can take a look at it

**Comment by watercrossing** [comment] 2016-01-05 16:56
This should be fixed by #2093. Please try it!

**Comment by SwartzCr** [comment] 2016-01-05 17:11
Ah, that makes total sense
don't add a specific 443 if there's a general one.

**Comment by SwartzCr** [comment] 2016-01-07 11:03
closing this since #2093 has been merged

**Closed by SwartzCr** 2016-01-07 11:03 UTC
Labels: apache, has pr
