### ISSUE TITLE
Site verification fails of acme-challenge file ends with newline

### ISSUE THREAD

**Issue by ctron** [letsencrypt/letsencrypt#1533] opened 2015-11-17 09:00 UTC
Using the `letsencrypt-auto` command in manual mode requires to create a challenge file under `.well-known/acme-challange`.

The file content should be the line printed out by the tool on the command line and be serves as "text/plain".

However if the file contains a newline, the validation fails.

Creating this file manually with an editor like `vi` automatically adds a newline to the end of the file.

IMHO this should be fixed to trim the string read from the web server before comparing.

**Comment by sjerdo** [comment] 2015-11-17 14:35
Duplicate of #1322.

**Closed** 2015-11-17 22:42 UTC
