### ISSUE TITLE
zope.interface error

### ISSUE THREAD

**Issue by felipedie** [letsencrypt/letsencrypt#2872] opened 2016-04-19 14:14 UTC
Traceback (most recent call last):
  File "./letsencrypt", line 7, in <module>
    from letsencrypt.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/letsencrypt/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface

**Comment by bmw** [comment] 2016-04-19 14:18
What is the output of `/root/.local/share/letsencrypt/bin/pip freeze | grep -i interface`?

**Comment by felipedie** [comment] 2016-04-19 14:21
/root/.local/share/letsencrypt/bin/pip freeze | grep -i interface
You are using pip version 8.0.3, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by felipedie** [comment] 2016-04-19 14:24
/root/.local/share/letsencrypt/bin/pip list
acme (0.5.0)
ConfigArgParse (0.10.0)
configobj (5.0.6)
enum34 (1.1.2)
funcsigs (0.4)
idna (2.0)
ipaddress (1.0.16)
letsencrypt (0.5.0)
letsencrypt-apache (0.5.0)
linecache2 (1.0.0)
mock (1.0.1)
ndg-httpsclient (0.4.0)
ordereddict (1.1)
parsedatetime (2.1)
pbr (1.8.1)
pip (8.0.3)
pyasn1 (0.1.9)
pycparser (2.14)
pyOpenSSL (0.15.1)
pyRFC3339 (1.0)
python-augeas (0.5.0)
python2-pythondialog (3.3.0)
pytz (2015.7)
requests (2.9.1)
setuptools (20.2.2)
six (1.10.0)
traceback2 (1.4.0)
unittest2 (1.1.0)
wheel (0.29.0)
zope.component (4.2.2)
zope.event (4.1.0)
You are using pip version 8.0.3, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by bmw** [comment] 2016-04-19 14:26
It appears `zope.interface` was not installed. This is strange.

I recommend:

1. Running `rm -rf /root/.local/share/letsencrypt`. This removes your installation of `letsencrypt`, but keeps all configuration files, certificates, logs, etc.
2. Make sure you have an up to date copy of `letsencrypt-auto`. It can be found [here](https://raw.githubusercontent.com/letsencrypt/letsencrypt/master/letsencrypt-auto).
3. Run `letsencrypt-auto` again.

If you get the same behavior, you can try installing `zope.interface` manually by running:
```
/root/.local/share/letsencrypt/bin/pip install zope.interface
```

**Comment by felipedie** [comment] 2016-04-19 14:32
[root@letsencrypt]# ./letsencrypt-auto --help --debug                                                                                
Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --help --debug
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/letsencrypt/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
[root@letsencrypt]# /root/.local/share/letsencrypt/bin/pip install zope.interface
Collecting zope.interface
Requirement already satisfied (use --upgrade to upgrade): setuptools in /root/.local/share/letsencrypt/lib/python2.7/dist-packages (from zope.interface)
Installing collected packages: zope.interface
Successfully installed zope.interface
You are using pip version 8.0.3, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Linux ip-10-11-180-115 3.14.20-20.44.amzn1.x86_64 #1 SMP Mon Oct 6 22:52:46 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I had already been these alternatives. unsuccessfully

**Comment by bmw** [comment] 2016-04-19 14:33
And after doing `/root/.local/share/letsencrypt/bin/pip install zope.interface` `letsencrypt-auto` still doesn't work?

**Comment by felipedie** [comment] 2016-04-19 14:35
Yes. still doesn't work.

**Comment by bmw** [comment] 2016-04-19 14:39
Looks like dupe of #2823. There are some known issues with AMIs which have not yet been resolved. Some people have had success with [this comment](https://github.com/letsencrypt/letsencrypt/issues/1680#issuecomment-170641501).

**Comment by felipedie** [comment] 2016-04-19 14:49
shit :P

I dosen't find this post. But , it works.


# pip install pip --upgrade
# pip install virtualenv --upgrade
# virtualenv -p /usr/bin/python27 venv27 
# . venv27/bin/activate 
# git clone https://github.com/letsencrypt/letsencrypt
# cd letsencrypt
# ./letsencrypt-auto certonly --debug --standalone -d <domain-name>

https://github.com/letsencrypt/letsencrypt/issues/1680#issuecomment-170641501

**Comment by bmw** [comment] 2016-04-19 14:51
Great! I'm glad it works.

**Closed by bmw** 2016-04-19 14:51 UTC
Labels: letsencrypt-auto, more-info

**Comment by rmed19** [comment] 2016-07-14 10:00
For me This cmd resolved the problem :
sudo unset PYTHON_INSTALL_LAYOUT

**Comment by jacobischwartz** [comment] 2016-08-01 18:13
@rmed19 that worked for me too, thanks!

**Comment by nohona** [comment] 2016-11-10 03:49
`pip install --upgrade pip`
and
`pip install virtualenv --upgrade`
then
`./certbot-auto renew`
did work

**Comment by stguitar** [comment] 2017-01-12 20:37
I just had to update stuff as @nohona pointed out.  Question is, is there anyway to prevent this from happening? I have been successful for a while on this server until today, which required me to run these update commands.

**Comment by ryan-williams** [comment] 2017-02-07 16:13
None of the above working for me…

```bash
$ pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages
$ pip install virtualenv --upgrade
Requirement already up-to-date: virtualenv in ./.local/lib/python2.7/site-packages
$ cd letsencrypt/
$ ./certbot-auto renew
Error: couldn't get currently installed version for /home/ec2-user/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/home/ec2-user/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/home/ec2-user/.local/share/letsencrypt/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
  File "/home/ec2-user/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
```

**Comment by swoodford** [comment] 2017-02-09 22:50
I'm running into this same problem:
`[root@www ec2-user]# /home/ec2-user/certbot-auto renew --debug
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt: 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
[root@www ec2-user]# `

**Comment by atmartins** [comment] 2017-02-12 13:54
Same problem on Digital Ocean:
`./certbot-auto renew
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt: 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
...`

**Comment by swoodford** [comment] 2017-02-14 17:12
I was able to work around my issue by starting over with the certbot installation and renewal process following current [instructions](https://certbot.eff.org/all-instructions/) on the website from the beginning.  I think the problem arose somewhere after updates to the underlying tools and since it had been so long since installing initially.

**Comment by PeterA1** [comment] 2017-02-19 09:56
I am having this problem now.  I have removed & reinstalled letsencrypt & certbot but consistently get the message...

`Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface`

Any advice much appreciated, my Cert expires in 24Hrs.

**Comment by jkuhs** [comment] 2017-02-20 16:04
I ran into the same issue on Amazon Linux today. Executing **certbot-auto** with **sudo** fixed it for me.

**Comment by brandonrich** [comment] 2017-03-08 11:39
I'm running as root on Amazon Linux.  This is a renewal; original cert installation was fine on this same machine.  I'm not sure what would have changed. 

I tried the above steps of updating pip and virtualenv... no luck. :-(  Cert expires in 9 days.

**Comment by RUSHt** [comment] 2017-03-08 11:44
I had lots of hassle, but found the following better than the CLI for my purposes.

https://github.com/Daplie/node-greenlock

**Comment by atomsymbol** [comment] 2017-04-10 15:25
This sequence of commands seems to have fixed the issue on my AWS instance:

    sudo yum install python-virtualenv python27-virtualenv "python*zope*"
    rm -rf ~/.local/share/letsencrypt
    ./certbot-auto --debug renew

Some of the installed packages might be redundant.

I also executed:

    ~/.local/share/letsencrypt/bin/pip install pip --upgrade
    ~/.local/share/letsencrypt/bin/pip install virtualenv --upgrade

but it seems to have had no effect.

**Comment by lifeofguenter** [comment] 2017-04-19 11:23
The following gist worked for me:

```
$ sudo -H pip install zope.interface -U
$ sudo -H pip install certbot -U
```

e.g. I had to "upgrade" `certbot` after installing `zope.interface`, even though I already installed `certbot` previously.

**Comment by ilamp** [comment] 2017-04-27 21:34
For anyone still having issues with AWS ami you can use following command to renew your certificates.

`unset PYTHON_INSTALL_LAYOUT; rm -rf /root/.local/share/letsencrypt/; /root/certbot-auto --debug renew`

**Comment by Namingwaysway** [comment] 2017-06-27 22:43
Part of the issue for me was related to some strange default behavior around 64 bit packages.

```
cd /root/.local/share/letsencrypt
\cp -r ./venv/lib64/* ./venv/lib/
```

Actually fixed the problem

**Comment by silicondales** [comment] 2017-08-22 09:20
Just to add some colour to the solution @lifeofguenter posted - solution for me on AWS linux when my update script fails seems to be different every time! This time, logged in as root `sudo su -` and a variety of updates did not work. Constantly getting zope.interface not set.

The solution last tried, which worked, was:

```
$ pip install zope.interface -U
$ pip install certbot -U
```
No sudo-ing (using as root)

But then `./certbot-auto --debug renew` failed again with the no zopa interface message. I then tried `sudo ./certbot-auto --debug renew` and this *worked*. Not clear why, it sort of shouldn't have. It hadn't worked before!

At some stage, I saw a reference to pip v 6.1.6 popping up, so its in there somewhere, but I removed and reinstalled all relevant stuff. AWS + root / sudo / letsencrypt maybe storing a dependency somewhere along the chain which is not updated when pip is updating?

**Comment by bentleymi** [comment] 2017-08-25 19:22
thank you @ilamp ! worked like a charm

**Comment by 0xnm** [comment] 2017-09-07 19:41
I'm using AWS Linux and had the same issue: "No module named interface error". I did the same what @ilamp proposed, but it didn't work. After I did the following, the issue was resolved:

    $ rm -rf /opt/eff.org

**Comment by Namingwaysway** [comment] 2017-09-08 17:12
Another update, since the install locations are different, again my issue was around the install location of the 64 bit packages on AWS by PIP.  This was fixed by installing once and then running

`\cp -r /opt/eff.org/certbot/venv/lib64/* /opt/eff.org/certbot/venv/lib/`

The location may need to change as the location of the installation files move with updates, but the general fix remained the same.

This was on an AWS AMI instance.

**Comment by silverbacknet** [comment] 2017-09-25 22:01
So I think I've figured out what the problem is: Anything that has C source or headers gets placed in /lib64 dist-packages, anything that doesn't lands in /lib. That means cffi, cryptography, and zope.interface.

**Comment by xavs** [comment] 2017-11-03 06:20
I was regularly doing the certbot-auto renew on an amazon ami.
One day it stopped working with that error.
All I had to do is: 
```
rm -rf ~/.local/share/letsencrypt
 sudo ./certbot-auto renew --debug
```

**Comment by apinder** [comment] 2017-12-28 11:21
Still seems to be an issue when renewing - even with

```
rm -rf ~/.local/share/letsencrypt
 sudo ./certbot-auto renew --debug
```

and/or 

```
unset PYTHON_INSTALL_LAYOUT; rm -rf /root/.local/share/letsencrypt/; /root/certbot-auto --debug renew;
```
As I've only got 24 hrs to renew this cert I think I'll just manually install the cert using a trusted CA instead as it seems to be a smoother process for AMI instances, it would be good to get this working smoothly though.

**Comment by ahmnouira** [comment] 2024-01-10 09:48
> The following gist worked for me:
> 
> ```
> $ sudo -H pip install zope.interface -U
> $ sudo -H pip install certbot -U
> ```
> 
> e.g. I had to "upgrade" `certbot` after installing `zope.interface`, even though I already installed `certbot` previously.

This works for me.
