### ISSUE TITLE
Let's Encrypt & Tor Hidden Service Protocol

### ISSUE THREAD

**Issue by a1exus** [letsencrypt/letsencrypt#2067] opened 2016-01-03 04:34 UTC
How would one use [Let's Encrypt](https://letsencrypt.org/) with [Tor: Hidden Service Protocol](https://www.torproject.org/docs/hidden-services.html.en)?

**Comment by schoen** [comment] 2016-01-03 04:38
Hi,

This is not possible right now.  There's a detailed discussion at

https://community.letsencrypt.org/t/if-when-will-le-support-onion-addresses/341/32

**Comment by bmw** [comment] 2016-01-05 22:50
Closing as a dupe of #91.

**Closed by bmw** 2016-01-05 22:50 UTC
