### ISSUE TITLE
Add --cert-key parameter

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#1973] opened 2015-12-21 21:34 UTC
Right now if someone wants to provide a specific key for their cert, they have to do so via the --csr option. However, generating a CSR with the proper subjectAlternativeNames is tedious and error prone. It would be nice to offer a --key parameter for this relatively common case.

Alternately, we might want to provide a gencsr subcommand to help people generate appropriate CSRs. This subcommand would also be a convenient place to stick options like --must-staple or --ecdsa.

**Comment by bmw** [comment] 2016-01-12 22:08
Dupe of #1491.

**Closed by bmw** 2016-01-12 22:08 UTC
Labels: ui / ux
