### ISSUE TITLE
webroot auth does not connect to https

### ISSUE THREAD

**Issue by ooxi** [letsencrypt/letsencrypt#2150] opened 2016-01-12 11:01 UTC
I have an https server running and wanted to use the webroot auth method. It seams like no attempt to connect to port 443 with https is being made. Is this correct if so will it change in the future? I cannot serve anything other than https on port 443 since all other ports are firewalled and 443 is a productive server which cannot be replaced by a http server.

**Comment by bmw** [comment] 2016-01-12 17:47
This is a duplicate of #1343 which is unfortunately a wontfix. See the #1343 for more information.

Your current options for using `letsencrypt` on a HTTPS only site is to use the `standalone` or `apache` plugins. More information on these plugins is available [here](https://letsencrypt.readthedocs.org/en/latest/using.html#plugins). Lastly, while not available yet, in the future you may be able to use the [DNS challenge](https://tools.ietf.org/html/draft-ietf-acme-acme-01#section-7.5) to obtain a cert for your site.

**Closed by bmw** 2016-01-12 17:47 UTC

**Comment by ooxi** [comment] 2016-01-13 09:52
Thanks for the information!
