### ISSUE TITLE
The webroot plugin is not working with CSR files

### ISSUE THREAD

**Issue by Tronde** [letsencrypt/letsencrypt#1989] opened 2015-12-22 22:04 UTC
Good evening guys,

I like to run the `letsencrypt-auto` client with the `webroot` plugin using an existing CSR file. Therefore I use the following command:

`/opt/letsencrypt/letsencrypt-auto certonly --webroot --webroot-path /var/www/example.com/public/ --server https://acme-staging.api.letsencrypt.org/directory --csr example.com.csr`

I got the following error code on stdout:
```
The webroot plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('--webroot-path must be set',)
```

The log shows the following:
```
2015-12-22 21:57:20,462:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-12-22 21:57:20,462:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-12-22 21:57:20,462:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.1
2015-12-22 21:57:20,462:DEBUG:letsencrypt.cli:Arguments: ['--webroot', '--webroot-path', '/var/www/example.com/public/', '--server', 'https://acme-staging.api.letsencrypt.org/directory', '--csr', 'example.com.csr']
2015-12-22 21:57:20,463:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-12-22 21:57:20,467:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2015-12-22 21:57:20,473:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 53, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-12-22 21:57:20,474:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-12-22 21:57:20,474:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
```

Without the `--csr example.com.csr` option the command completes without any errors.

Is here something wrong, or is it not possible to use the webroot plugin with a given csr file?

I am running Ubuntu 14.04.3 LTS with Python 2.7.6. If you need more information for troubleshooting, please tell me.

Best regards,
Tronde

**Comment by osirisinferi** [comment] 2015-12-24 17:58
Isn't this issue a duplicate of https://github.com/letsencrypt/letsencrypt/issues/1802 ?

**Closed** 2016-01-05 20:36 UTC
Labels: webroot

**Comment by Tronde** [comment] 2016-01-09 18:13
Hello,

I believe this issue was accidentally closed. I run the command from my initial post and get the same error again. And I got the same error again.

I could not see why this issue should be a duplicate of #1802 but I tried the following command that was mentioned to be successful:
```
/opt/letsencrypt/letsencrypt-auto --renew certonly --server https://acme-v01.api.letsencrypt.org/directory --csr sub.domain.csr -a webroot --webroot-map '{"sub.domain.tld" : "/tmp"}'
```

While running this command I get the error:
```
letsencrypt: error: unrecognized arguments: --webroot-map{"sub.domain.tld": "/tmp"}
```

Could someone look into this again, please?

**Comment by bmw** [comment] 2016-01-12 01:09
@Tronde, I closed this issue because I agreed that this was a duplicate of #1802. Both issues identify that you cannot use `-w` or `--webroot-path` with `--csr`. They both identified that when you do, you get the following error:
```
The webroot plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('--webroot-path must be set',)
```

The temporary solution until #1802 is resolved is to use `--webroot-map`, including all of the domains in the CSR in the map. This works, however, if you forget a space between `--webroot-map` and its argument, you'll see something like:
```
letsencrypt: error: unrecognized arguments: --webroot-map{"sub.domain.tld": "/tmp"}
```

Make sure you include a space between `--webroot-map` and the argument you provide it and try running the client again. If you still do not believe this is a duplicate of #1802, please explain to me how this issue is different and I will consider reopening.

**Comment by Tronde** [comment] 2016-01-12 06:46
Thank you for your explanation.

I missed the space between ```--webroot-map``` and the argument. With the space I'm able to request a certificate with my CSR file.

Thanks again for your help.

**Comment by centminmod** [comment] 2016-01-17 09:05
yup encounter this bug still and --webroot-map doesn't seem to work if i'm trying to pass a variable to it https://community.letsencrypt.org/t/csr-and-webroot-path-webroot-map-errors/8986
