### ISSUE TITLE
PluginError: --webroot-path must be set

### ISSUE THREAD

**Issue by roydejong** [letsencrypt/letsencrypt#1722] opened 2015-12-04 09:47 UTC
I'm getting this error message:

    The webroot plugin is not working; there may be problems with your existing configuration.
    The error was: PluginError('--webroot-path must be set',)

However, I *am* supplying this parameter:

    ./letsencrypt-auto certonly --webroot --webroot-path /var/www

Here's the relevant log output:

    2015-12-04 09:43:20,063:DEBUG:letsencrypt.cli:Root logging level set at 30
    2015-12-04 09:43:20,064:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
    2015-12-04 09:43:20,065:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.0
    2015-12-04 09:43:20,065:DEBUG:letsencrypt.cli:Arguments: ['--webroot', '--webroot-path', '/var/www']
    2015-12-04 09:43:20,067:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
    2015-12-04 09:43:20,071:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
    2015-12-04 09:43:20,076:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
    Traceback (most recent call last):
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 54, in prepare
    self.option_name("path")))
    PluginError: --webroot-path must be set
    2015-12-04 09:43:20,076:DEBUG:letsencrypt.display.ops:No candidate plugin
    2015-12-04 09:43:20,076:DEBUG:letsencrypt.cli:Selected authenticator None and installer None

I'm using version 0.1.0 of the letsencrypt client.

**Comment by sjerdo** [comment] 2015-12-04 09:51
Duplicate of #1668

**Comment by bmw** [comment] 2015-12-10 20:39
Yes. Closing as a dupe of #1668.

**Closed by bmw** 2015-12-10 20:39 UTC
