### ISSUE TITLE
Hanging threads (acme.standalone)

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1085] opened 2015-10-22 18:19 UTC

**Comment by kuba** [comment] 2015-10-27 20:44
Steps to reproduce: `while python acme/acme/standalone_test.py; do echo -n .; done` and wait for hang. Interestingly, stracing to the child thread unblocks it:

```
jakub@iks:~/dev/letsencrypt/letsencrypt$ strace -p 12897
Process 12897 attached
futex(0x1ef17a0, FUTEX_WAIT_PRIVATE, 0, NULL^CProcess 12897 detached
 <detached ...>
jakub@iks:~/dev/letsencrypt/letsencrypt$ strace -p 12903
Process 12903 attached
select(4, [3], [], [], NULL)            = -1 EBADF (Bad file descriptor)
stat("/usr/lib/python2.7/threading.py", {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
open("/usr/lib/python2.7/threading.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f65d9f98000
read(3, "\"\"\"Thread module emulating a sub"..., 8192) = 8192
read(3, "ore threads to wait until they a"..., 4096) = 4096
read(3, "                endtime = _time("..., 4096) = 4096
read(3, " with blocking set to false, do "..., 4096) = 4096
read(3, "f.__cond.__init__(Lock())\n\n    d"..., 4096) = 4096
read(3, "initialized = True\n        # sys"..., 4096) = 4096
read(3, "       if __debug__:\n           "..., 4096) = 4096
read(3, "rwrites the (if any) thread curr"..., 4096) = 4096
read(3, "def ident(self):\n        \"\"\"Thre"..., 4096) = 4096
read(3, "# Dummy thread class to represen"..., 4096) = 4096
read(3, "f-test code\n\ndef _test():\n\n    c"..., 4096) = 2280
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f65d9f98000, 4096)            = 0
stat("/usr/lib/python2.7/threading.py", {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
stat("/usr/lib/python2.7/SocketServer.py", {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
open("/usr/lib/python2.7/SocketServer.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f65d9f98000
read(3, "\"\"\"Generic socket server classes"..., 8192) = 8192
read(3, " at all other times.\n           "..., 4096) = 4096
read(3, " TCPServer(BaseServer):\n\n    \"\"\""..., 4096) = 4096
read(3, "\"Internal routine to wait for ch"..., 4096) = 4096
read(3, "or request handler classes.\n\n   "..., 4096) = 3556
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f65d9f98000, 4096)            = 0
stat("/usr/lib/python2.7/SocketServer.py", {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
write(2, "Exception in thread Thread-3:\nTr"..., 529) = 529
write(2, "\n", 1)                       = 1
futex(0x1ef17a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1b49850, FUTEX_WAKE_PRIVATE, 1) = 1
madvise(0x7f65d61a2000, 8368128, MADV_DONTNEED) = 0
_exit(0)                                = ?
+++ exited with 0 +++
```

**Comment by kuba** [comment] 2015-10-27 20:49
Similarly, there is a problem with `while python letsencrypt/plugins/standalone_test.py; do echo -n .; done`:

```
jakub@iks:~/dev/letsencrypt/letsencrypt$ strace -p 17397
Process 17397 attached
futex(0x2e43590, FUTEX_WAIT_PRIVATE, 0, NULL^CProcess 17397 detached
 <detached ...>
jakub@iks:~/dev/letsencrypt/letsencrypt$ strace -p 17422
Process 17422 attached
select(4, [3], [], [], NULL)            = -1 EBADF (Bad file descriptor)
stat("/usr/lib/python2.7/threading.py", {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
open("/usr/lib/python2.7/threading.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fec6cdbc000
read(3, "\"\"\"Thread module emulating a sub"..., 8192) = 8192
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fec6766a000
read(3, "ore threads to wait until they a"..., 4096) = 4096
read(3, "                endtime = _time("..., 4096) = 4096
read(3, " with blocking set to false, do "..., 4096) = 4096
read(3, "f.__cond.__init__(Lock())\n\n    d"..., 4096) = 4096
read(3, "initialized = True\n        # sys"..., 4096) = 4096
read(3, "       if __debug__:\n           "..., 4096) = 4096
read(3, "rwrites the (if any) thread curr"..., 4096) = 4096
read(3, "def ident(self):\n        \"\"\"Thre"..., 4096) = 4096
read(3, "# Dummy thread class to represen"..., 4096) = 4096
read(3, "f-test code\n\ndef _test():\n\n    c"..., 4096) = 2280
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7fec6cdbc000, 4096)            = 0
stat("/usr/lib/python2.7/threading.py", {st_mode=S_IFREG|0644, st_size=47336, ...}) = 0
stat("/home/jakub/dev/letsencrypt/letsencrypt/acme/acme/standalone.py", {st_mode=S_IFREG|0644, st_size=6764, ...}) = 0
open("/home/jakub/dev/letsencrypt/letsencrypt/acme/acme/standalone.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=6764, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=6764, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fec6cdbc000
read(3, "\"\"\"Support for standalone client"..., 8192) = 6764
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7fec6cdbc000, 4096)            = 0
stat("/usr/lib/python2.7/SocketServer.py", {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
open("/usr/lib/python2.7/SocketServer.py", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fec6cdbc000
read(3, "\"\"\"Generic socket server classes"..., 8192) = 8192
read(3, " at all other times.\n           "..., 4096) = 4096
read(3, " TCPServer(BaseServer):\n\n    \"\"\""..., 4096) = 4096
read(3, "\"Internal routine to wait for ch"..., 4096) = 4096
read(3, "or request handler classes.\n\n   "..., 4096) = 3556
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7fec6cdbc000, 4096)            = 0
stat("/usr/lib/python2.7/SocketServer.py", {st_mode=S_IFREG|0644, st_size=24036, ...}) = 0
write(2, "Exception in thread Thread-3:\nTr"..., 656) = 656
write(2, "\n", 1)                       = 1
futex(0x2e43590, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2306f30, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x2306f30, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x22e0d30, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x2306f30, FUTEX_WAKE_PRIVATE, 1) = 1
madvise(0x7fec676aa000, 8368128, MADV_DONTNEED) = 0
_exit(0)                                = ?
+++ exited with 0 +++
```

**Comment by devnsec-com** [comment] 2015-10-27 23:16
I've reproduced this bug.

I added some extra `print` outputs in the python file to help locate the issue.

stracing the letsencrypt/plugins/standalone_test.py, the main thread:
```
write(2, "test_run_stop_dvsni (letsencrypt"..., 75) = 75
write(2, " ... ", 5)                    = 5
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(3, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("0.0.0.0")}, 
16) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0
.0.0.0")}, [16]) = 0
listen(3, 5)                            = 0
clone(child_stack=0x7f8f2d8ebff0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIG
HAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CL
EARTID, parent_tidptr=0x7f8f2d8ec9d0, tls=0x7f8f2d8ec700, child_tidptr=0x7f8f2d
8ec9d0) = 7505
futex(0x55dcac2fe030, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 
ffffffff) = 0
futex(0x55dcab8e82a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 
ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
getsockname(3, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0
.0.0.0")}, [16]) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0
.0.0.0")}, [16]) = 0
futex(0x55dcab8e82a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 
ffffffff) = 0
futex(0x55dcab8e82a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55dcab8e82a0, FUTEX_WAKE_PRIVATE, 1) = 0
write(1, "Getting instance ...\n", 21)  = 21
futex(0x55dcab8e82a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 
ffffffff) = 0
write(1, "Logging ...\n", 12)           = 12
futex(0x55dcab8e82a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 
ffffffff) = -1 EAGAIN (Resource temporarily unavailable)
getsockname(3, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0
.0.0.0")}, [16]) = 0
write(1, "Calling server.shutdown2 ...\n", 29) = 29
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 4
getsockname(3, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
connect(4, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
close(4)                                = 0
close(3)                                = 0
write(1, "Calling thread.join ...\n", 24) = 24
futex(0x55dcac2fe030, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
futex(0x55dcac2fe030, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
futex(0x55dcac2fe030, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
futex(0x55dcac2fe030, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff
```

the thread that running the `serve_forever2()`:
```
set_robust_list(0x7f8f2d8ec9e0, 24)     = 0
futex(0x55dcac2fe030, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55dcab8e82a0, FUTEX_WAKE_PRIVATE, 1) = 0
getsockname(3, {sa_family=AF_INET, sin_port=htons(60893), sin_addr=inet_addr("0.0.0.0")}, [16]) = 0
futex(0x55dcab8e82a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55dcab8e82a0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, ffffffff) = 0
futex(0x55dcab8e82a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x55dcab8e82a0, FUTEX_WAKE_PRIVATE, 1) = 0
select(4, [3], [], [], NULL
```

Here's what happened in my understanding:

1. **T1** creates the listening socket **SOCK3**
2. **T1** creates and starts thread **T2**
3. **T2** calling `select` on the **SOCK3**, and being blocked by it
4. **T1** creates the client socket **SOCK4**, and tried to connect to the listening port
5. **T1** closes both sockets **SOCK3** and **SOCK4**, but **T2** is still blocking by `select` on **SOCK3**
6. **T1** joins **T2**, and results in deadlock

Note:
* **T1** is the main thread
* **T2** is the `serve_forever2()` thread
* **SOCK3** is the listening socket which has fd=3 in the strace log
* **SOCK4** is the client socket tried to connect to listening socket, it has fd=4 in the strace log

I would guess, the root cause of the issue is the blocked `select` function call will not return if the socket has closed by another thread.

**Comment by devnsec-com** [comment] 2015-10-27 23:31
I've wrote a test python script to reproduce this:

```python
import threading
import socket
import select


def thread_func(s):
    print("calling select() ...")
    ret_val = select.select([s], [], [], None)
    print("select() has returned %s" % repr(ret_val))


sock = socket.socket()
sock.listen()
t = threading.Thread(target=thread_func, args=(sock,))
t.start()
print("closing socket ...")
sock.close()
print("socket has closed.")
t.join()
```

The running result of it will be something looks like this:
```
calling select() ...
closing socket ...
socket has closed.
( hangs here )
```

**Comment by bmw** [comment] 2015-10-30 01:22
I'm closing this as a result of #1200. While I'm not certain #1200 solved the problem, we have no reports of the problem occurring using the code in that PR. If that changes, this should be reopened.

**Closed by bmw** 2015-10-30 01:22 UTC
Labels: acme, bug
