### ISSUE TITLE
Error in Ubuntu Server 12 using Apache/2.2.22

### ISSUE THREAD

**Issue by i-rme** [letsencrypt/letsencrypt#1580] opened 2015-11-20 18:53 UTC
Ubuntu 12.04.5 LTS
Apache/2.2.22 (running)

Command:
```
./letsencrypt-auto --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
```

OUTPUT
```
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --apache --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Unable to parse runtime variables',)
```

DEBUG LOG /var/log/letsencrypt/letsencrypt.log
```
2015-11-20 18:47:20,204:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-20 18:47:20,205:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-20 18:47:20,205:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151114
2015-11-20 18:47:20,205:DEBUG:letsencrypt.cli:Arguments: ['--apache', '--server', 'https://acme-v01.api.letsencrypt.org/directory', '--agree-dev-preview']
2015-11-20 18:47:20,206:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-20 18:47:20,220:DEBUG:letsencrypt.cli:Requested authenticator apache and installer apache
2015-11-20 18:47:20,936:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#apache): Unable to parse runtime variables
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 150, in prepare
    self.aug, self.conf("server-root"), self.conf("ctl"))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/parser.py", line 39, in __init__
    self.update_runtime_variables(ctl)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/parser.py", line 104, in update_runtime_variables
    raise errors.PluginError("Unable to parse runtime variables")
PluginError: Unable to parse runtime variables
2015-11-20 18:47:20,943:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-11-20 18:47:20,943:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
```

**Comment by bmw** [comment] 2015-11-20 20:41
Dupe of #1208

**Closed by bmw** 2015-11-20 20:41 UTC
