### ISSUE TITLE
Installing - Command exited with error code 1

### ISSUE THREAD

**Issue by greeny** [letsencrypt/letsencrypt#1315] opened 2015-11-04 07:38 UTC
Hi, I recently cloned letsencrypt and then run this command (domain excluded):

    sudo ./letsencrypt-auto -d ***.org -d apps.***.org --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory run

But I got this output:

    Updating letsencrypt and virtual environment dependencies.....
    Command "/root/.local/share/letsencrypt/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-7rYtbY/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NJW_HS-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-7rYtbY/cryptography

Can you help me fix it?

**Comment by pde** [comment] 2015-11-04 08:03
You don't need to run "letsencrypt-auto" with sudo; it will call sudo itself for the particular tasks that require root.  If you get the same error when running as a user, can you paste the full output of
`./letsencrypt-auto -vvvvvv --debug -t`?

**Comment by greeny** [comment] 2015-11-04 08:11
Full output:

http://pastebin.com/xCw6YCyV

**Comment by kuba** [comment] 2015-11-04 08:12
`virtual memory exhausted: Cannot allocate memory`

**Comment by kuba** [comment] 2015-11-04 08:13
Are you running `letsencrypt-auto` on some embedded system? If not, free up some memory! :)

**Comment by greeny** [comment] 2015-11-04 08:14
I see it now, but the problem is, I am on VPS, where I have limited RAM to 1 GB

**Comment by pde** [comment] 2015-11-04 08:18
Ok, closing as a dupe of #1081.

**Closed by pde** 2015-11-04 08:18 UTC

**Comment by nanohard** [comment] 2015-12-26 02:22
Debian 8 VPS, 6GB RAM, 6GB swap, same error. I don't think swap is being used, or even all 6GB of RAM. Could the issue lie elsewhere?
