### ISSUE TITLE
Multiple VirtualHost directives in single conf file doesn't work well

### ISSUE THREAD

**Issue by shield-9** [letsencrypt/letsencrypt#2574] opened 2016-03-01 09:55 UTC
When I've tried `./letsencrypt-auto certonly --apache --keep -d aigis.pw`, I got an notice: **We were unable to find a vhost with a ServerName or Address of aigis.pw.**

There are some vhost directives in one of my Apache config files (For example, /etc/httpd/conf.d/ssl-vhosts.conf) and it seems that config file is not parsed by this client as expected.

Using Client version 0.4.1 and CentOS 7.2.

**Comment by basilgohar** [comment] 2016-03-01 18:12
I have an example (real values anonymized) like that right here that had this problem.  xyz.tld is not detected.
```
<VirtualHost 123.123.123.123:80>
    ServerName xyz.tld
    ServerAlias *.xyz.tld

    DocumentRoot /home/abc/wp3

    <Directory /home/abc/wp3>
        Require all granted
        AllowOverride All
        Options All
        DirectoryIndex index.php
    </Directory>

</VirtualHost>

<VirtualHost 123.123.123.123:80>
    ServerName abc.tld
    ServerAlias *.abc.tld

    DocumentRoot /home/abcwp3

    <Directory /home/abc/wp3>
        Require all granted
        AllowOverride All
        Options All
        DirectoryIndex index.php
    </Directory>

</VirtualHost>
```

**Comment by bmw** [comment] 2016-03-01 20:56
dupe of #1024. Thanks for providing more information though. I'll reference this issue in #1024 so the info can be used when developing a fix.

**Closed by bmw** 2016-03-01 20:56 UTC

**Comment by basilgohar** [comment] 2016-03-01 22:34
I think you meant #2320?
