### ISSUE TITLE
letsencrypt-auto fails to parse Apache config file

### ISSUE THREAD

**Issue by paulschreiber** [letsencrypt/letsencrypt#1598] opened 2015-11-22 17:50 UTC
letsencrypt-auto fails to parse one of my Apache config files:
```
$ ./letsencrypt-auto --apache --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory -d paulschreiber.com 
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: sudo /home/paul/.local/share/letsencrypt/bin/letsencrypt --apache --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory -d paulschreiber.com
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/semacode.com.conf', u'Syntax error'),)
```

Here's the `/etc/apache2/sites-enabled/semacode.com.conf` file:
```
<VirtualHost *:80>
  ServerName      semacode.com
  ServerAlias     www.semacode.com
  DocumentRoot    /data/sites/semacode.com/
  TransferLog     /data/logs/semacode.com/access
  ErrorLog        /data/logs/semacode.com/error
  Redirect        /posts/rss              http://semacode.com/feed
  Redirect        permanent   /weblog                 http://semacode.com/blog

#ProxyPreserveHost On
#  ProxyPass /past http://old.semacode.com
  #ProxyPassReverse /past http://old.semacode.com
#<proxy>
 # Order allow,deny
  #Allow from all
#</proxy>

  Redirect /stylesheets/inside.css http://old.semacode.com/stylesheets/inside.css
  RedirectMatch /images/portal/(.*) http://old.semacode.com/images/portal/$1
  Redirect /images/invisible.gif http://old.semacode.com/images/invisible.gif
  RedirectMatch /javascripts/(.*) http://old.semacode.com/javascripts/$1

  RewriteEngine on
  RewriteRule ^/past/(.*)                 http://old.semacode.com/past/$1 [L,P]
  RewriteCond %{HTTP_HOST}                !^semacode\.com$ [NC]
  RewriteCond %{HTTP_HOST}                !^$
  RewriteRule ^/(.*)                      http://semacode.com/$1 [L,R]

</VirtualHost>


<VirtualHost *:80>
  ServerName old.semacode.com
  ServerAlias www.old.semacode.com
  DocumentRoot /home/simon/semacode-server/semacode/website/trunk/public
  TransferLog     /data/logs/semacode.com/access-old
  ErrorLog        /data/logs/semacode.com/error-old
  <Directory "/home/simon/semacode-server/semacode/website/trunk/public">
    Options FollowSymLinks
    AllowOverride None
    Order allow,deny
    Allow from all
  </Directory>
</VirtualHost>
```

**Comment by pde** [comment] 2015-11-22 19:51
I believe this is a duplicate of #1531 and https://github.com/hercules-team/augeas/issues/307.

**Closed** 2015-11-22 19:51 UTC
Labels: apache, duplicate
