### ISSUE TITLE
The new letsencrypt-auto is broken on amazon linux...

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2433] opened 2016-02-11 03:52 UTC
```
[Process-11 : client 8 ami-60b6c60a amazonlinux-2015.09.1]
server ec2.Instance(id='i-30d2a1b0') at 52.87.228.112
ec2-user@52.87.228.112
[ec2-user@52.87.228.112] put: letest-1455162344/le.tar.gz -> /home/ec2-user/le.tar.gz
[ec2-user@52.87.228.112] run: tar xzf le.tar.gz
[ec2-user@52.87.228.112] put: scripts/test_letsencrypt_auto_certonly_standalone.sh -> /home/ec2-user/test_letsencrypt_auto_certonly_standalone.sh
[ec2-user@52.87.228.112] run: ./test_letsencrypt_auto_certonly_standalone.sh 
[ec2-user@52.87.228.112] out: + cd letsencrypt
[ec2-user@52.87.228.112] out: + ./letsencrypt-auto --os-packages-only
[ec2-user@52.87.228.112] out: WARNING: Amazon Linux support is very experimental at present...
[ec2-user@52.87.228.112] out: if you would like to work on improving it, please ensure you have backups
[ec2-user@52.87.228.112] out: and then run this script again with the --debug flag!
[ec2-user@52.87.228.112] out: + ./letsencrypt-auto certonly --no-self-upgrade -v --standalone --debug --text --agree-dev-preview --agree-tos --renew-by-default --redirect --register-unsafely-without-email --domain ec2-52-87-228-112.compute-1.amazonaws.com --server http://172.31.54.176:4000/directory
[ec2-user@52.87.228.112] out: Creating virtual environment...
[ec2-user@52.87.228.112] out: Already using interpreter /usr/bin/python2.7
[ec2-user@52.87.228.112] out: New python executable in /home/ec2-user/.local/share/letsencrypt/bin/python2.7
[ec2-user@52.87.228.112] out: Also creating executable in /home/ec2-user/.local/share/letsencrypt/bin/python
[ec2-user@52.87.228.112] out: Installing setuptools, pip...done.
[ec2-user@52.87.228.112] out: Installing Python packages...
[ec2-user@52.87.228.112] out: Had a problem while downloading and verifying Python packages:
[ec2-user@52.87.228.112] out: Downloading argparse==1.4.0 (23K)...
[ec2-user@52.87.228.112] out: Downloading cffi==1.4.2 (365K)...
[ec2-user@52.87.228.112] out: Downloading ConfigArgParse==0.10.0 (36K)...
[ec2-user@52.87.228.112] out: Downloading configobj==5.0.6 (33K)...
[ec2-user@52.87.228.112] out: Downloading cryptography==1.1.2 (349K)...
[ec2-user@52.87.228.112] out: Downloading enum34==1.1.2 (46K)...
[ec2-user@52.87.228.112] out: Downloading funcsigs==0.4 (14K)...
[ec2-user@52.87.228.112] out: Downloading idna==2.0 (61K)...
[ec2-user@52.87.228.112] out: Downloading ipaddress==1.0.16 (17K)...
[ec2-user@52.87.228.112] out: Downloading linecache2==1.0.0 (12K)...
[ec2-user@52.87.228.112] out: Downloading ndg-httpsclient==0.4.0 (24K)...
[ec2-user@52.87.228.112] out: Downloading ordereddict==1.1 (2K)...
[ec2-user@52.87.228.112] out: Downloading parsedatetime==1.5 (50K)...
[ec2-user@52.87.228.112] out: Downloading pbr==1.8.1 (89K)...
[ec2-user@52.87.228.112] out: Downloading psutil==3.3.0 (261K)...
[ec2-user@52.87.228.112] out: Downloading pyasn1==0.1.9 (36K)...
[ec2-user@52.87.228.112] out: Downloading pycparser==2.14 (223K)...
[ec2-user@52.87.228.112] out: Downloading pyOpenSSL==0.15.1 (102K)...
[ec2-user@52.87.228.112] out: Downloading pyRFC3339==1.0 (8K)...
[ec2-user@52.87.228.112] out: Downloading python-augeas==0.5.0 (90K)...
[ec2-user@52.87.228.112] out: Downloading python2-pythondialog==3.3.0 (1831K)...
[ec2-user@52.87.228.112] out: Downloading pytz==2015.7 (476K)...
[ec2-user@52.87.228.112] out: Downloading requests==2.9.1 (501K)...
[ec2-user@52.87.228.112] out: Downloading six==1.10.0 (10K)...
[ec2-user@52.87.228.112] out: Downloading traceback2==1.4.0 (16K)...
[ec2-user@52.87.228.112] out: Downloading unittest2==1.1.0 (96K)...
[ec2-user@52.87.228.112] out: Downloading Werkzeug==0.11.3 (305K)...
[ec2-user@52.87.228.112] out: Downloading zope.component==4.2.2 (546K)...
[ec2-user@52.87.228.112] out: Downloading zope.event==4.1.0 (476K)...
[ec2-user@52.87.228.112] out: Downloading zope.interface==4.1.3 (141K)...
[ec2-user@52.87.228.112] out: Downloading acme==0.4.0 (95K)...
[ec2-user@52.87.228.112] out: Downloading letsencrypt==0.4.0 (197K)...
[ec2-user@52.87.228.112] out: Downloading letsencrypt-apache==0.4.0 (93K)...
[ec2-user@52.87.228.112] out: Downloading mock==1.0.1 (818K)...
[ec2-user@52.87.228.112] out: You are using pip version 6.0.8, however version 8.0.2 is available.
[ec2-user@52.87.228.112] out: You should consider upgrading via the 'pip install --upgrade pip' command.
[ec2-user@52.87.228.112] out: Processing /tmp/peep-suA_8p/argparse-1.4.0-py2.py3-none-any.whl
[ec2-user@52.87.228.112] out: Installing collected packages: argparse
[ec2-user@52.87.228.112] out: 
[ec2-user@52.87.228.112] out: Successfully installed argparse-1.4.0
[ec2-user@52.87.228.112] out: You are using pip version 6.0.8, however version 8.0.2 is available.
[ec2-user@52.87.228.112] out: You should consider upgrading via the 'pip install --upgrade pip' command.
[ec2-user@52.87.228.112] out: Processing /tmp/peep-9VZTvR/cffi-1.4.2.tar.gz
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     unable to execute 'gcc': No such file or directory
[ec2-user@52.87.228.112] out:     unable to execute 'gcc': No such file or directory
[ec2-user@52.87.228.112] out:         No working compiler found, or bogus compiler options
[ec2-user@52.87.228.112] out:         passed to the compiler from Python's distutils module.
[ec2-user@52.87.228.112] out:         See the error messages above.
[ec2-user@52.87.228.112] out:         (If they are about -mno-fused-madd and you are on OS/X 10.8,
[ec2-user@52.87.228.112] out:         see http://stackoverflow.com/questions/22313407/ .)
[ec2-user@52.87.228.112] out:     Complete output from command python setup.py egg_info:
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Package libffi was not found in the pkg-config search path.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     Perhaps you should add the directory containing `libffi.pc'
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     to the PKG_CONFIG_PATH environment variable
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     No package 'libffi' found
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     unable to execute 'gcc': No such file or directory
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     unable to execute 'gcc': No such file or directory
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:         No working compiler found, or bogus compiler options
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:         passed to the compiler from Python's distutils module.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:         See the error messages above.
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:         (If they are about -mno-fused-madd and you are on OS/X 10.8,
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:         see http://stackoverflow.com/questions/22313407/ .)
[ec2-user@52.87.228.112] out:     
[ec2-user@52.87.228.112] out:     ----------------------------------------
[ec2-user@52.87.228.112] out:     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-GeAlCq-build
[ec2-user@52.87.228.112] out: 

ami-60b6c60a - amazonlinux-2015.09.1 FAIL


letsencrypt.log
--------------------------------------------------------------------------------

[ec2-user@52.87.228.112] sudo: if [ -f /var/log/letsencrypt/letsencrypt.log ]; then     cat /var/log/letsencrypt/letsencrypt.log; else echo "[novarlog]"; fi
[ec2-user@52.87.228.112] out: [novarlog]
[ec2-user@52.87.228.112] out: 

[ec2-user@52.87.228.112] sudo: if [ -f ./letsencrypt.log ]; then     cat ./letsencrypt.log; else echo "[nolocallog]"; fi
[ec2-user@52.87.228.112] out: [nolocallog]
[ec2-user@52.87.228.112] out: 
```

**Comment by pde** [comment] 2016-02-11 04:13
Strangely, I couldn't reproduce this by spinning up an AMI by hand...

**Comment by erikrose** [comment] 2016-02-11 15:49
FWIW, I doubt this is a regression, since the problem is a missing compiler, and we use the same bootstrap script as the old le-auto.

**Comment by erikrose** [comment] 2016-02-11 16:03
This is a duplicate of #2432: since we run it with --no-self-upgrade, it doesn't bootstrap, so gcc doesn't get installed.

**Closed by erikrose** 2016-02-11 16:03 UTC
Labels: letsencrypt-auto
