### ISSUE TITLE
Can't renew certificate in Debian Wheezy

### ISSUE THREAD

**Issue by gbeddow** [letsencrypt/letsencrypt#2817] opened 2016-04-12 15:02 UTC
Hi,

I've run into a problem in letsencrypt-auto with renewing the certificates I created back in December and January.

Back then, both creation and renewal worked fine, but renewal in the past few days fails consistently (haven't tried creation recently).

The server is running Debian Wheezy 7.10.

I've tried a lot of variations with different flags to letsencrypt-auto, uninstalling and reinstalling letsencrypt-auto, and with uninstalling and reinstalling python, python-dev and other packages to no avail.

Here's some typical output from trying to renew:

```
# /root/letsencrypt/letsencrypt-auto certonly --renew-by-default -a webroot --webroot-path /ReadyNAS-Volume/public_html --email email@example.com --text --agree-tos -d example.com -d www.example.com auth
Bootstrapping dependencies for Debian-based OSes...
Ign http://apt.readynas.com 6.4.2 InRelease
Hit http://apt.readynas.com 6.4.2 Release.gpg
Hit http://apt.readynas.com 6.4.2 Release
Hit http://apt.readynas.com 6.4.2/updates armel Packages
Hit http://apt.readynas.com 6.4.2/apps armel Packages
Hit http://apt.readynas.com 6.4.2/main armel Packages
Hit http://apt.readynas.com 6.4.2/updates armhf Packages
Hit http://apt.readynas.com 6.4.2/apps armhf Packages
Hit http://apt.readynas.com 6.4.2/main armhf Packages
Ign http://mirrors.kernel.org wheezy InRelease
Hit http://mirrors.kernel.org wheezy Release.gpg
Hit http://mirrors.kernel.org wheezy Release
Hit http://mirrors.kernel.org wheezy/main armel Packages
Hit http://mirrors.kernel.org wheezy/main armhf Packages
100% [Connecting to security.debian.org (2001:4f8:8:36::1deb:19)]                                                                                                    9,024 kB/s 0s^Hit http://security.debian.org wheezy/updates InRelease
Hit http://security.debian.org wheezy/updates/main armel Packages
Hit http://security.debian.org wheezy/updates/contrib armel Packages
Hit http://security.debian.org wheezy/updates/non-free armel Packages
Hit http://security.debian.org wheezy/updates/main armhf Packages
Hit http://security.debian.org wheezy/updates/contrib armhf Packages
Hit http://security.debian.org wheezy/updates/non-free armhf Packages
Reading package lists... Done
/root/letsencrypt/letsencrypt-auto: 182: /root/letsencrypt/letsencrypt-auto: lsb_release: not found
/root/letsencrypt/letsencrypt-auto: 184: /root/letsencrypt/letsencrypt-auto: lsb_release: not found
No libaugeas0 version is available that's new enough to run the
Let's Encrypt apache plugin...
Reading package lists... Done
Building dependency tree
Reading state information... Done
libssl-dev is already the newest version.
ca-certificates is already the newest version.
gcc is already the newest version.
augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
dialog is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
The following package was automatically installed and is no longer required:
  librtmp0
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking for new version...
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2283, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 938, in main
    never_download=options.never_download)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1054, in create_environment
    install_pip(py_executable, search_dirs=search_dirs, never_download=never_download)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 643, in install_pip
    filter_stdout=_filter_setup)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 976, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

There was a similar issue reported at:

[https://github.com/letsencrypt/letsencrypt/issues/1554](https://github.com/letsencrypt/letsencrypt/issues/1554)

with identical Traceback output, but there was no resolution there.

Any ideas on this one? Thanks.

**Comment by bmw** [comment] 2016-04-12 19:06
I'm sorry there hasn't yet been a resolution on #1554 but this is a duplicate of that issue. I'm closing this issue and I will respond on #1554.

**Closed by bmw** 2016-04-12 19:06 UTC
