### ISSUE TITLE
Should .well-known/acme-challenge be removed?

### ISSUE THREAD

**Issue by phpdan** [letsencrypt/letsencrypt#2049] opened 2015-12-31 04:49 UTC
After running "./letsencrypt-auto certonly --webroot -w /some/path -d thedomain" successfully, should .well-known/acme-challenge be removed? It was not on my system.

**Comment by bmw** [comment] 2016-01-05 22:38
Thanks for the report @phpdan. `.well-known/acme-challenge` should be removed, but this is a dupe of #1003.

**Closed by bmw** 2016-01-05 22:38 UTC

**Comment by alanhogan** [comment] 2016-03-25 21:52
Whew. I just saw this in my Dreamhost account and it gave me a bit of a scare.

**Comment by ozh** [comment] 2016-03-28 16:46
Heh. Same. You guys should ping Dreamhost about this, it's awesomly awesome that they're providing 1-click install for Let's Encrypt certs, but this hidden dir should be removed afterwards...

**Comment by jerrygarciuh** [comment] 2016-04-08 17:00
Same here.  What a relief that it's not an intrusion.

**Comment by mariomara** [comment] 2017-09-22 13:24
Phew!
