### ISSUE TITLE
Error creating new authz

### ISSUE THREAD

**Issue by xstaticxgpx** [letsencrypt/letsencrypt#1283] opened 2015-11-02 05:02 UTC
Looking at old issues, this is caused by DNS look up issues on the ACME server?

I'm trying to register domains un1x.su/www.un1x.su (I got the beta invite email listing those domains)

Is the system expecting the PTR for the requesting IP to point to the domain? I'm trying to run from a residential server... any insight you guys could provide would be great.

```
$  python -V
Python 2.7.3

$ cat /var/log/letsencrypt/letsencrypt.log
2015-11-02 04:53:01,252:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151021
2015-11-02 04:53:01,252:DEBUG:letsencrypt.cli:Arguments: ['--agree-dev-preview', '-d', 'un1x.su', '-d', 'www.un1x.su', '--server', 'https://acme-v01.api.letsencrypt.org/directory', 'auth']
..
2015-11-02 04:53:07,201:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '76', 'Expires': 'Mon, 02 Nov 2015 04:53:07 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 Nov 2015 04:53:07 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '_ZSYqA04L34Sj_GWpfFD2Xx9XtnQ7NIN5m0RUYpnwiA'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-02 04:53:07,202:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/user/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1087, in main
    return args.func(args, config, plugins)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 463, in auth
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 303, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
```

**Comment by kuba** [comment] 2015-11-02 06:33
This is a duplicate of https://github.com/letsencrypt/letsencrypt/issues/1138. I have added a note in https://github.com/letsencrypt/letsencrypt/wiki/Known-issues#users.

@jsha is working on the fix, on the CA side: https://github.com/letsencrypt/boulder/issues/1048, https://github.com/letsencrypt/boulder/pull/1065.

**Closed by kuba** 2015-11-02 06:33 UTC
Labels: duplicate

**Comment by akram** [comment] 2015-11-24 08:18
Hi @kuba @jsha  letsencrypt/boulder#1048, letsencrypt/boulder#1065 seems now to be closed resp. merged , and I still face the issue with letsencrypt 0.0.0.dev20151123 .

Is it now required to vendor boulder in letsencrypt head to have this issue fix?

**Comment by jsha** [comment] 2015-11-24 17:28
@akram: There could be any number of issues causing this particular error message. Could you post with details of what you've tried and your domain name on https://community.letsencrypt.org? Thanks!

**Comment by akram** [comment] 2015-11-25 09:14
@jsha thanks, I've posted it as a client issue https://community.letsencrypt.org/t/4447
