### ISSUE TITLE
documentation - clarification of manual mode

### ISSUE THREAD

**Issue by centminmod** [letsencrypt/letsencrypt#1311] opened 2015-11-04 03:00 UTC
Not sure when or where it started but on the forums, a few folks have got the incorrect idea than manual mode and webroot authentication doesn't need SSH/terminal access 

but AFAIK, unless something has changed https://letsencrypt.readthedocs.org/en/latest/using.html#plugins manual mode as well as webroot authentication still needs SSH/terminal access just not on the same server for manual ? That is still the case ?

**Comment by kuba** [comment] 2015-11-04 06:27
Manual mode does not need SSH/terminal access. When it stops to prompt the user  it displays the following message (https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151030/letsencrypt/plugins/manual.py#L42-L53):

```
Make sure your web server displays the following content at {uri} before continuing:

{validation}

Content-Type header MUST be set to {ct}.

If you don't have HTTP server configured, you can run the following command on the target server (as root):

{command}
```

The displayed example command does require SSH and terminal access. You could however set `{validation}` and `{ct}` using other methods. Indeed, we might need to clarify this in #1137.

**Comment by kuba** [comment] 2015-11-04 06:28
I'll close it as a dupe of #1137.

**Closed by kuba** 2015-11-04 06:28 UTC
Labels: documentation

**Comment by centminmod** [comment] 2015-11-05 08:38
okay thanks @kuba
