### ISSUE TITLE
Standalone authenticator doesn't properly shut down web server on error exit

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#918] opened 2015-10-07 18:05 UTC
Steps to reproduce:

Run

`letsencrypt --server SERVER_PATH --no-verify-ssl --authenticator standalone --text --agree-eula --agree-tos -d 1.le-test.hoffman-andrews.com auth  `

Ensure the authentication fails somehow. In my case it specifically failed with a 400 in POST /acme/challenge/..... One way to accomplish a similar thing would be to run a local Boulder, do a successful LE run (to set up the registration), then bring down Boulder and try another LE run.

Then run another authorization request.

Expected result:

Success, or another failure.

Actual result:

`The program letsencrypt (process ID 12717) is already listening on TCP port 443.
This will prevent us from binding to that port. Please stop the letsencrypt
program temporarily and then try again.`

**Comment by kuba** [comment] 2015-10-07 18:11
Would you mind trying out #895 to see if the problem is fixed, @jsha ?

**Comment by bmw** [comment] 2015-10-09 21:54
I struggled to recreate this, but it seems unlikely this a problem in #895 with the switch to threads.

**Comment by bmw** [comment] 2015-10-20 03:03
Fixed in #895.

**Closed by bmw** 2015-10-20 03:03 UTC
