### ISSUE TITLE
letsencrypt fails with "AttributeError: 'NoneType' object has no attribute 'lower'"

### ISSUE THREAD

**Issue by phispi** [letsencrypt/letsencrypt#2247] opened 2016-01-20 19:29 UTC
letsencrypt failed on our server when parsing our apache2.4 config. It turned out that the config files where the error happens are standard apache2 modules.
The error message is `"AttributeError: 'NoneType' object has no attribute 'lower'" in letsencrypt_apache/parser.py", line 311`.

We created pull request #2105 to demonstrate this behavior and to help with TTD ;-).

Thanks for providing this great project!

**Comment by pde** [comment] 2016-01-20 22:39
So this is a duplicate of #2105, right?

**Comment by pde** [comment] 2016-01-20 22:41
Assigning this to 0.4.0 though it would be great to get a fix for the imminent 0.3.0 release.

**Comment by phispi** [comment] 2016-01-21 22:06
Yes, that's the bug report corresponding to the pull request with the test showing the problem.

**Comment by SwartzCr** [comment] 2016-02-19 17:50
this is a fun bug!
```
(Pdb) matches
[u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/dav_svn.load/IfModule/directive', u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/dav_svn.load/IfModule/IfModule/directive', u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/authz_svn.load/directive', u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/authz_svn.load/IfModule/directive', u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/dav.load/IfModule/directive']
(Pdb) matches = self.aug.match("%s//*[self::directive=~regexp('%s')]" % (start, regex))
(Pdb) matches
[u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/authz_svn.load/directive', u'/files/tmp/tmp2pLutJtemp/debian_apache_2_4/two_vhost_80/apache2/mods-enabled/authz_svn.load/IfModule/directive']
```
it seems that we're doing something to get rid of some of our matches so that when we later call get on things that were previously in the match list, they're no longer there

**Closed** 2016-02-22 23:37 UTC
Labels: apache
