### ISSUE TITLE
Won't accept email

### ISSUE THREAD

**Issue by EvanCarroll** [letsencrypt/letsencrypt#1865] opened 2015-12-11 07:52 UTC
When I run `letsencrypt-auto certonly` it asks for my email, however it won't accept it. My email address is me <at> evancarroll dot com.

**Comment by pde** [comment] 2015-12-11 20:37
What error did you get?  I can't reproduce your problem.

**Comment by frankf-cgn** [comment] 2015-12-12 11:13
Might it be that there is no A Record for the domain of the email-address? Test it with `ping  evancarroll dot com`. If this is the case look aorund here in the issues, as far as I understand the lets encrypt team is working on this. Until a proper fix is published, you might simply add an A record for the domain.

**Comment by EvanCarroll** [comment] 2015-12-12 19:48
This is definitely what happened then. There was a time when my domain had no A Record. What an obtuse error. Do you have a link to the bug report? @frankf-cgn

**Comment by devster31** [comment] 2015-12-13 01:43
letsencrypt/boulder#1197 I believe it is

**Comment by pde** [comment] 2015-12-13 18:53
Closing this ticket since this isn't a client bug.

**Closed by pde** 2015-12-13 18:53 UTC
Labels: boulder
