### ISSUE TITLE
 --keep-until-expiring requires interaction if no certificate update 

### ISSUE THREAD

**Issue by cfairweather** [letsencrypt/letsencrypt#2831] opened 2016-04-14 06:20 UTC
Running a command of `./letsencrypt-auto --config /opt/letsencrypt.ini certonly --keep-until-expiring --agree-tos -d my.domain.com ` with configuration file contents that includes the option `text = True` results in prompted input if certificates are not yet due for removal, breaking automated scripts.

## STR:
1. Request certificates using let's encrypt (using the options provided below).
2. Request certificates again using `--keep-until-expiring` flag set and a configuration file that specifies `text = True`, the same that should have been used for the first request:
  2. An example command would be `./letsencrypt-auto --config /opt/letsencrypt.ini certonly --keep-until-expiring --agree-tos -d my.domain.com`
  2. with a configuration file of:
  ```
# Let's Encrypt Configuration with defaults
# All flags used by the client can be configured here. Run Let's Encrypt with
# "--help" to learn more about the available options.

# Use a 4096 bit RSA key instead of 2048
rsa-key-size = 4096

# Uncomment and update to register with the specified e-mail address
email = EMAIL_HERE@EMAIL_HERE

# Uncomment and update to generate certificates for the specified
# domains.
# domains = example.com, www.example.com
# Always provide domains via env. See letsencrypt-run.sh

# Uncomment to use a text interface instead of ncurses
text = True

# Uncomment to use the standalone authenticator on port 443
# authenticator = standalone
# standalone-supported-challenges = tls-sni-01

# Uncomment to use the webroot authenticator. Replace webroot-path with the
# path to the public_html / webroot folder being served by your web server.
authenticator = webroot
webroot-path = /var/www/challenges
```

## Expected:
1. Let's Encrypt client prints:
```
------------------------------------------------------------------------------- 
Certificate not yet due for renewal; no action taken.                           
------------------------------------------------------------------------------- 
```
and does not prompt for input afterward, allowing the client to exit with a code of `0`.

## Actual:
1. Let's Encrypt client prints:
```
------------------------------------------------------------------------------- 
Certificate not yet due for renewal; no action taken.                           
------------------------------------------------------------------------------- 
Press Enter to Continue
```
and requires interaction from a tty before exiting cleanly. 

## Environment
- OS = Ubuntu 14.04.2 
- Webserver = nginx, but using certonly since acme-challenges are successfully handled through an existing nginx server. The `letsencrypt.ini` file specifies the correct challenge directory for the client by providing the options 
  - 
  ```
authenticator = webroot
webroot-path = /var/www/challenges
```

### Notes
Let's Encrypt was installed by running and then calling:
```
git clone https://github.com/letsencrypt/letsencrypt
./letsencrypt-auto --config /opt/letsencrypt.ini certonly --keep-until-expiring --agree-tos -d my.domain.com
```

**Comment by bmw** [comment] 2016-04-14 14:55
Thank you for taking the time to write such a detailed bug report.

It looks like this bug was introduced in our last release. It will be fixed in our next release, but in meantime you can use the non-interactive option to ensure the client won't block on user input. From the output of `letsencrypt --help all`:

```
  -n, --non-interactive, --noninteractive
                        Run without ever asking for user input. This may
                        require additional command line flags; the client will
                        try to explain which ones are required if it finds one
                        missing (default: False)
```

If you set this flag on the command line or in your config file, the client will not prompt and you'll see your expected behavior.

**Comment by cfairweather** [comment] 2016-04-14 16:01
Thanks for providing a workaround! I'll implement that in the meantime. Sorry, I didn't look in the output, I tried searching through the documentation online for the `--keep-until-expiring` details and the `text` configuration option. 😅

**Closed** 2016-04-21 17:48 UTC
Labels: bug, has pr, renewal, ui / ux
