### ISSUE TITLE
Fails when site using both IPv4 + IPv6

### ISSUE THREAD

**Issue by highacid** [letsencrypt/letsencrypt#2323] opened 2016-01-31 05:05 UTC
Hello,

I have deployed IPv6 stack on my cpanel accounts, it seems all the accounts with IPv6 in place they fail with this error. Updating letsencrypt and virtual environment dependencies......Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly --config /tmp/ff2vqViFmo.conf --renew-by-defaultFailed authorization procedure. ipv6.highacid.com (http-01): urn:acme:error:unknownHost :: The server could not resolve a domain name :: No IPv4 addresses found for ipv6.highacid.comIMPORTANT NOTES: - The following errors were reported by the server: Domain: ipv6.highacid.com Type: urn:acme:error:unknownHost Detail: No IPv4 addresses found for ipv6.highacid.com.

**Comment by schoen** [comment] 2016-02-16 22:20
This is a server-side issue; the Let's Encrypt CA doesn't yet support IPv6 validations. You can get a cert for an IPv6-only host using the DNS challenge if you can make DNS zone updates (although our Python client doesn't support the DNS challenge and you would need to use an alternative client).

Duplicate of letsencrypt/boulder#593.

**Closed by schoen** 2016-02-16 22:20 UTC
