### ISSUE TITLE
Execute standalone comand will result :Error creating new authz

### ISSUE THREAD

**Issue by ddload** [letsencrypt/letsencrypt#1525] opened 2015-11-17 02:47 UTC
Hi,
when I run `./letsencrypt-auto certonly -a standalone -d www.example.com --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview` for twice,the program give me a error like:
```
An unexpected error occurred.
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
Please see the logfiles in /var/log/letsencrypt for more details.
```
env:freebsd 10.2,under jail
the full error trace:
```
2015-11-17 02:43:41,771:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-17 02:43:41,774:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-17 02:43:41,775:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151114
2015-11-17 02:43:41,775:DEBUG:letsencrypt.cli:Arguments: ['-a', 'standalone', '-d', 'www.example.com', '--server', 'https://acme-v01.api.letsencrypt.org/directory', '--agree-dev-preview']
2015-11-17 02:43:41,777:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-17 02:43:41,789:DEBUG:letsencrypt.cli:Requested authenticator standalone and installer None
2015-11-17 02:43:42,141:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x80a735a90>
Prep: True
2015-11-17 02:43:42,143:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x80a735a90> and installer None
2015-11-17 02:43:42,171:DEBUG:letsencrypt.cli:Picked account: <Account(ed9d08c013969e13af340fd7f462ec05)>
2015-11-17 02:43:42,173:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-17 02:43:42,181:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-17 02:43:43,185:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-17 02:43:43,189:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Tue, 17 Nov 2015 02:40:28 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 17 Nov 2015 02:40:28 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'm7pGUOgnXpa-VJsy7C6r_3DlLgaqvhENX6bhNnvM198'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-17 02:43:43,189:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Tue, 17 Nov 2015 02:40:28 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 17 Nov 2015 02:40:28 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'm7pGUOgnXpa-VJsy7C6r_3DlLgaqvhENX6bhNnvM198'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-17 02:43:44,149:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0001_key-letsencrypt.pem
2015-11-17 02:43:44,154:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0001_csr-letsencrypt.pem
2015-11-17 02:43:44,155:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0001_csr-letsencrypt.pem', data='0\x82\x02\x900\x82\x01x\x02\x01\x000\x1c1\x1a0\x18\x06\x03U\x04\x03\x0c\x11www.example.com0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xfbc\xda\xd9\xfe7g\xed26\x14\xac\x10\xa1@\xfc$p^<\x041\xb2\x88\xa7n\x99\xbf\x86\xe6n\xaf\xc0\xd9|i\x9fk\rXe,\x9d\x02Hthg\xab\x0c\xaf\xe5\x85\xb1\x10\xf4\x98\xbe(6\xc0R7\xee\x10\xf1\xa4\xe6\x9c\x86\xf3\xa9\x1b\xce\x86\xda\x00D\xfeTf\xfc\x19\x15\x8f\xe1\xef\x9d\xd6\xb5\xeb_\xaf&@\x17A\xda\xbb\x80\xe5Of\x15B\n\xf5\xc7\xa13A\xf9M\xc3N\x91\xc0{r\xb1%\x11\xabtH\xa0\x08>\x191\x17\xad\x93\xaf\x1b\xdc\xcc\xda\x9c\x90\xf9_\x14\x00,\n4\xa4\x9a\x9d;\x81]>:\xd8\xe2C\xd4\x87\xf7_\x86?\x12L\xb0\x99R:\xcbw\'\xaa\x8dl(\xa8\x97c\xb5\x96\xfa\x99\x8d#\xc0(\xa5\xd2\x8e^\x991\x9d[\xfe\x15i\\"\xf0\x9a\x96\xe0\xd4\xa2\xdf\x0cB\x89\xb4\xa0P\xe9\x14R\xd3\x86\xed\xcb\x81\xfc\xacd\xd3_\x84\xd8\xd7\x13\xf3r\xdb\xac\xe4\x92\xfe\x82\xd0v\xc7Lw\xceS\xb6\x0c\xb8rE\xba\x91\x92C\x19\x02\x03\x01\x00\x01\xa0/0-\x06\t*\x86H\x86\xf7\r\x01\t\x0e1 0\x1e0\x1c\x06\x03U\x1d\x11\x04\x150\x13\x82\x11www.example.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00\x82\x85hr\x17\xff\xd1\xb6=f\xb4\x04C\x18w`\x07\x81\x7fw\xaa8\x07f\x87)\x96*\x1c\x94\xe8/\xbd\xec;\n4)ze\xa7\xc9\xc4!\xedK\x90:\x1e\xfb\xf1/?$\xfb\n\x93s\x8a\xca\x98z2\xbe\xa3\xb4y}\xcf\x15\xd0\xee\x0b\xe4\x1c0y\xd1\x0b\xc5\x0e\'\xd9(k\x13!\xcb$*\x05!\xc7\xf0$\xed\xac\x0c\xdeFR\xba\x13tZ5\x86\x92E2\x06\x95\x1c\xec\xb6U7\xce\x1b\r\xf02\x1e4\x0eMC\xb5\t\xd8\x8bQh\x8cu\x1a\xcf\xcf\x1eb\x95\xbe\x9e\xe5\xfa\xfa\xd9Z\x00\xda\xd2j\xad;\xf1x\xf1\x12\xe4\xe7n\x86B\x0b\x10L\x86|\xe9b.M\x1cQ\xc3g\xde\xfeIa\x84\xea\xf6\xa2\x9as\xb0bt_](\xd05\xf1\x89\xfdny\xc3\xeb8^\x8f\x1e\x03\x9b\xe4).u\xef\xde\x85\xf9\xb7\xfek\x8bA\x96\x96\xfbI\xc8\x0f\x1f\x08\xca\x9d7\x9f]\xecR\xd8\x87~\xb8\x12|\xc1\x04\x83q!w\x1a\xda\x89\xeb4\xd1\xdbX\xfa', form='der'), domains: ['www.example.com']
2015-11-17 02:43:44,156:DEBUG:root:Requesting fresh nonce
2015-11-17 02:43:44,156:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-11-17 02:43:44,158:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-17 02:43:45,087:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-11-17 02:43:45,091:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Tue, 17 Nov 2015 02:40:30 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 17 Nov 2015 02:40:30 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'BUfBoTa2tXJ_rbvlQpRKNwfVsYWCzRJRBQBc4EeFYbg'}. Content: ''
2015-11-17 02:43:45,091:DEBUG:acme.client:Storing nonce: '\x05G\xc1\xa16\xb6\xb5r\x7f\xad\xbb\xe5B\x94J7\x07\xd5\xb1\x85\x82\xcd\x12Q\x05\x00\\\xe0G\x85a\xb8'
2015-11-17 02:43:45,092:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, challenges=None, status=None, combinations=None
2015-11-17 02:43:45,092:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "www.example.com"}, "resource": "new-authz"}
2015-11-17 02:43:45,094:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), x5t=None, jku=None, x5tS256=None, cty=None, kid=None, x5u=None, alg=None, jwk=None, typ=None
2015-11-17 02:43:45,097:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), x5t=None, nonce=None, jku=None, x5tS256=None, cty=None, kid=None, x5u=None, typ=None
2015-11-17 02:43:45,098:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "4eg6bghYeAA1Tb65a97A1G84xe5jTjb-XDYCr3Ezk9Junf4vEuzyYmDpPGZKR5DQLGM_mVbJnEeL1I4j9LtdMe-jh_vD5knvZSsrWIWQYGlY7z9-x5NbdcQzJcXDgwCevoOX2WoLOp_huii_UFdgvLaQIfyrrJVtqYy2J7m07t53BxTs7PAD3klr3pk6LlPCLWowpH9m8ZMIvw9SLNmys1vK2-mWK7AddIOFoN3dgpupKYNzEDvHQyhPzqgTTmtgQm__oE2op9LEWce8viYxkZMYsgxykZERv-AqZI5HbDQBUQxh3Jl8-uCOtSmsNMqxMPziWh9vPW-bVTh1gSlp-w"}}, "protected": "eyJub25jZSI6ICJCVWZCb1RhMnRYSl9yYnZsUXBSS053ZlZzWVdDelJKUkJRQmM0RWVGWWJnIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJ3d3cuZGRsb2FkaXZ5LmNvbSJ9LCAicmVzb3VyY2UiOiAibmV3LWF1dGh6In0", "signature": "j-ahhVGsn9uiWAGBFHPTshEwNLGBOVMT0Oq279JlcfmWbQE1uC2sqX6_iXFCflx_wIug4a9GEuRQzl2-nf_Ba3RrpRrH8Xzwyv_c5SEjOy5wEjqqCLbWmR5p_iUfm0GslzDa3jYI7pJN5xOlYzx40dYp0FBiYPzFLjN1mhU8X4b8gLjOCrJ2qftWb6Y1xmic9bvKzARoun6J8Bim3HkPPG022ofexIurgaYumcxnaE48qdSYTUYk8zxlRCCPS-29i5MxtejKbycPqog5eyGyc7AA-FOIRbWPr51gJxYCc7o2uWnPkY7zamHR_dWeVgjat6pZ7A7QXwKTfoK8voIwXg"}'}
2015-11-17 02:43:45,100:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-17 02:43:48,116:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 500 76
2015-11-17 02:43:48,120:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '76', 'Expires': 'Tue, 17 Nov 2015 02:40:33 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 17 Nov 2015 02:40:33 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'pO6J6VbkXfcUj73j1D78V7aFFi3Fq5xRszyRl8Mf33g'}. Content: '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-17 02:43:48,120:DEBUG:acme.client:Storing nonce: '\xa4\xee\x89\xe9V\xe4]\xf7\x14\x8f\xbd\xe3\xd4>\xfcW\xb6\x85\x16-\xc5\xab\x9cQ\xb3<\x91\x97\xc3\x1f\xdfx'
2015-11-17 02:43:48,120:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '76', 'Expires': 'Tue, 17 Nov 2015 02:40:33 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 17 Nov 2015 02:40:33 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'pO6J6VbkXfcUj73j1D78V7aFFi3Fq5xRszyRl8Mf33g'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-17 02:43:48,123:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1187, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 497, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 326, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 254, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 237, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 195, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 628, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 544, in _check_response
    raise messages.Error.from_json(jobj)
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
```

**Comment by bmw** [comment] 2015-11-17 23:28
This is actually a known issue, being a duplicate of #1327. Thanks for including your logs though. I referenced this issue there so they can be used for debugging.

**Closed by bmw** 2015-11-17 23:28 UTC
