### ISSUE TITLE
Can't renew, missing symlink

### ISSUE THREAD

**Issue by lewiswalsh** [letsencrypt/letsencrypt#1733] opened 2015-12-04 11:36 UTC
Foolishly, I have managed to remove the keys and symlinks for a domain. I now can't generate a new set, and `lets-encrypt-auto` fails with the following:

```
2015-12-04 11:16:04,301:DEBUG:letsencrypt.storage:Expected symlink /etc/letsencrypt/live/mydomain.com/cert.pem for cert does not exist.
2015-12-04 11:16:04,312:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/lewis/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/lewis/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/home/lewis/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 512, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/home/lewis/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 318, in _auth_from_domains
    lineage = _treat_as_renewal(config, domains)
  File "/home/lewis/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 230, in _treat_as_renewal
    config, domains)
  File "/home/lewis/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 204, in _find_duplicative_certs
    candidate_names = set(candidate_lineage.names())
  File "/home/lewis/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 459, in names
    with open(target) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found

```

**Comment by bmw** [comment] 2015-12-10 23:08
Dupe of #1195.

**Closed by bmw** 2015-12-10 23:08 UTC
