### ISSUE TITLE
Error creating new authz :: Name is not whitelisted

### ISSUE THREAD

**Issue by jackerzhou** [letsencrypt/letsencrypt#1426] opened 2015-11-09 09:41 UTC
2015-11-09 09:38:54,785:DEBUG:letsencrypt.cli:Root logging level set at -10
2015-11-09 09:38:54,786:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-09 09:38:54,786:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.0.dev0
2015-11-09 09:38:54,786:DEBUG:letsencrypt.cli:Arguments: ['--server', 'https://acme-v01.api.letsencrypt.org/directory', '-vvvv', '--text', '--agree-dev-preview', '--agree-tos', '-a', 'standalone', '-d', 'avlmetrics.com']
2015-11-09 09:38:54,786:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-09 09:38:54,786:DEBUG:letsencrypt.cli:Requested authenticator standalone and installer None
2015-11-09 09:38:54,931:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x27a9c90>
Prep: True
2015-11-09 09:38:54,931:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x27a9c90> and installer None
2015-11-09 09:38:54,950:DEBUG:letsencrypt.cli:Picked account: <Account(84346c889f7708206ca4813c2b8b56bc)>
2015-11-09 09:38:54,950:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-09 09:38:54,956:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-09 09:38:55,115:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-09 09:38:55,118:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Contr
ol': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 09 Nov 2015 09:38:55 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'fFze57Y_8h00qX5mU1OosZh2iCOSmd0n5XUKw3q-aX0'}. Content: '{"new-authz":"htt
ps://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-09 09:38:55,119:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cach
e', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 09 Nov 2015 09:38:55 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'fFze57Y_8h00qX5mU1OosZh2iCOSmd0n5XUKw3q-aX0'}): '{"new-aut
hz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-09 09:38:55,209:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0002_key-letsencrypt.pem
2015-11-09 09:38:55,213:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-letsencrypt.pem
2015-11-09 09:38:55,214:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0002_csr-letsencrypt.pem', data='0\x82\x02\x890\x82\x01q\x02\x000\x191\x170\x15\x06\x03U\x04\x03\x0c\x0eavlmetrics.com0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x0
1\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\x9eHF\x0e\xf0x\x04\xca\xe5\xba"\xc8\xfc\xfbS\xf8\x82\xc9"\xb9&\x02qW\xa2\x1b\xda\xf9\xa6\xf0\x0e>+\xadd\xe8\'VJ^^e=Q\xe0\xb4GBq+\x10\xfcG\xf2MN>\x15?9j?j\x8f\xa4\xed\x94L\xca\xf8G\x02|\x9b\xf82\xbb\xe5\xdbv\x9e\x9e\x91\n\x1e\x06
"g\xe2\x82\xd4|\xea\x8cTy\xe6h\xd8\xc4\x18\x84\xdc#V\xb5f{n,\xaa\xaf\xfeX\xd5E\xfb%\xa3\xec\x902\x95\xccly;\xcd\xc0\x00\xeb\x18\x9b\xc4o.\x83\xb3\nTJ\xeaX\xde\xf39\xbe\x7f\x89\xb1\x1b_\xf9\x9a\xda\x84E\x19\x143\xa9\n\xf8z\xb3\xf55\xb6p\x9f\xfe}7\xd5\xed\xcf@Y\xb8\xd7\x
bd5\xc2^\x86P\x81\x98\xfc\xd2l[\xe9\xf9g\xfe\xa5O\xb0[\xea\x84\xec\xbf\xb5\xb62L\xf3\x8d\xc5\xebI\xb0\x0e\xec\x9b\xf4j\xb1\xbe(\xa1&\x18I\xf6\x92#\x85#T\xa7d\xa3\xf2J\xf5\xe5\x1f(fX\x9esBHr\x8e\x1e:\x83\xf8p\x88Y\x02\x03\x01\x00\x01\xa0,0*\x06\t*\x86H\x86\xf7\r\x01\t\x
0e1\x1d0\x1b0\x19\x06\x03U\x1d\x11\x04\x120\x10\x82\x0eavlmetrics.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00@^\x84\x1a\x18j\xaf\xfb\x11\xbd\x19\xe6\x02\xd0\xfa\x15\xe0\xde\t\xa0\xf6\xe4\xd3\x07\x10#\xb8\xf6a\x9d\xc4\xa0T\xcd\x0b\t\x98J\x1e\xc0
\xd6\xfa\xe6\xf5\xc8C\x95\x91\x7fC\xdc\x86,\x0e \x9f>&\xdbM\x03\x9e\xaf&\xb9c#\x1e)\x12Y\xd25\xf7$9\xd8<\xb3M\xd6\xe0\x10\x08\xba\xa0\xea\xd4\x99\x18~\xdf\xba\xb2\xfa\x1f$\x04 \xad\xbd<`\x87F"xq\x86\xb6\xf1\xa2A\xf9\x97\xe3T2pa\x8a\xa5L\x83$\x86\x86\xb2\xb9g\xf7d\xca }
\xbc\x15\xbf\xd8\x1b_\x01EP\x07>V$\xa2#\xc2/\xa1|\xe6\xfenG\xd0\x9a\xd4\xd2[[\x1f@\x07~\xf5W\xfb~\x1b\xd8\xeev\xb6%>^\xa3c\xb6g\xca\xb2\xd6\x9d\xf8d9&\x12\x199\x12a\xa2\xeeQ.\xee\xea\xbe\xdaN\x97*\xb6\xb6^\xfd\xed\xb5_\x83\x96\x00[N\x87t\x96n\xf3\x08\x9d\xab\xf4\\\x9c4
JfM\xa3\x7f\xba\xef\xd7\x16\xc9\xd7D\xf5\x81Z3\xe4\x04\x90\xd7\x96\xd0u\xed', form='der'), domains: ['avlmetrics.com']
2015-11-09 09:38:55,214:DEBUG:root:Requesting fresh nonce
2015-11-09 09:38:55,214:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-11-09 09:38:55,216:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-09 09:38:55,288:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-11-09 09:38:55,291:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-st
ore', 'Date': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'Tx4TVXrwLCyA_7sOrDRFJLRLG914SeyVYgj9ZwSwqCM'}. Content: ''
2015-11-09 09:38:55,292:DEBUG:acme.client:Storing nonce: 'O\x1e\x13Uz\xf0,,\x80\xff\xbb\x0e\xac4E$\xb4K\x1b\xddxI\xec\x95b\x08\xfdg\x04\xb0\xa8#'
2015-11-09 09:38:55,292:DEBUG:acme.jose.json_util:Omitted empty fields: challenges=None, expires=None, combinations=None, status=None
2015-11-09 09:38:55,292:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "avlmetrics.com"}, "resource": "new-authz"}
2015-11-09 09:38:55,294:DEBUG:acme.jose.json_util:Omitted empty fields: kid=None, x5c=(), alg=None, jwk=None, typ=None, crit=(), jku=None, cty=None, x5tS256=None, x5u=None, x5t=None
2015-11-09 09:38:55,297:DEBUG:acme.jose.json_util:Omitted empty fields: kid=None, x5c=(), crit=(), typ=None, jku=None, cty=None, x5tS256=None, x5u=None, x5t=None, nonce=None
2015-11-09 09:38:55,297:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "tdkOqaU23MYRA86hTDJRps0cgQDK3exylprzHETY3WtiyS8EoRgEtGaceEcn
Ucx3OPUP2L3_Ybtn54l21I3Oukfk6TOb1gjLghUdbpf6JjNUELS9zKZVrjG4r3LL45Teg4huA6Z6EmsT2UqF_MOGezYIv5-mJOdq23byM71wnA28a-K9KpppiXzmfIugiKMjjeaq_zw9Oxn5_T37JWEEgilQK79x4gVyD7ATXwiRW7qC7Vtcuz7DWtWV-l3A28FDuPBjlvRj_h4hzLenhtaUOv9ynxg37VfQP8i1Ip-2U_Hb1ltHk0ODpXk8zRbWzftDScD2tNbrn
BcCXufGc1nC6Q"}}, "protected": "eyJub25jZSI6ICJUeDRUVlhyd0xDeUFfN3NPckRSRkpMUkxHOTE0U2V5Vllnajlad1N3cUNNIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJhdmxtZXRyaWNzLmNvbSJ9LCAicmVzb3VyY2UiOiAibmV3LWF1dGh6In0", "signature": "Zf06WO3cTFTLyaff0OS
hVg2Gkvdno0JfkJqcLr_6rg_RWuplsDft-jlZbYDRMm5lkcV8xlG5MqkB9epIWjbf70NIe4SQhiNLuQREfFzWmBJPAZVynXosuf-acA-pytZsHTKpZ5MRsWZHT_fQTqeMxtm2UTOAAw7AZHnkY6LRp0AOgVjePuBRXDB60C9gqRIdMpdnVeIYhQRSGJA0aSDNbGaW-wJxVgUNz6GsLcXLP5eDvrWv9_WW1wQgO5iFH8n5hS4d0cim1fjfsCwfDK6HcTzjobVxFPM-
FHOMYWvSNF4TW-e56r4lXmWe2LSB617JLortYtcO9WBHy3-N6k5Y2g"}'}
2015-11-09 09:38:55,299:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-09 09:38:55,390:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 403 101
2015-11-09 09:38:55,392:DEBUG:root:Received <Response [403]>. Headers: {'Content-Length': '101', 'Expires': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 
09 Nov 2015 09:38:55 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '6FSv1dGha7ToyvvSoU4w5RLpXwxMgz3-ZRgyRqnCMCw'}. Content: '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Name is not whitelisted"}'
2015-11-09 09:38:55,393:DEBUG:acme.client:Storing nonce: '\xe8T\xaf\xd5\xd1\xa1k\xb4\xe8\xca\xfb\xd2\xa1N0\xe5\x12\xe9_\x0cL\x83=\xfee\x182F\xa9\xc20,'
2015-11-09 09:38:55,393:DEBUG:acme.client:Received response <Response [403]> (headers: {'Content-Length': '101', 'Expires': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store'
, 'Date': 'Mon, 09 Nov 2015 09:38:55 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '6FSv1dGha7ToyvvSoU4w5RLpXwxMgz3-ZRgyRqnCMCw'}): '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Name is not whitelisted"}'
2015-11-09 09:38:55,395:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "./letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.0.dev0', 'console_scripts', 'letsencrypt')()
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/cli.py", line 1140, in main
    return args.func(args, config, plugins)
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/cli.py", line 490, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/cli.py", line 328, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/local/python27/lib/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 628, in post
    return self._check_response(response, content_type=content_type)
  File "build/bdist.linux-x86_64/egg/acme/client.py", line 544, in _check_response
    raise messages.Error.from_json(jobj)
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted

**Comment by ghw** [comment] 2015-11-09 10:30
You need to apply for Beta Invite Closed
https://docs.google.com/forms/d/15Ucm4A20y2rf9gySCTXD6yoLG6Tba7AwYgglV7CKHmM/viewform?edit_requested=true

**Comment by bmw** [comment] 2015-11-09 22:18
Since this is a dupe of #1287, I'm closing this issue.

As for resolving the issue, I'm assuming you got an invite into the beta program. Did your beta invite say that the exact name `avlmetrics.com` was whitelisted? Please feel to follow up here, #1287, or #letsencrypt on Freenode. The last option will probably get you the fastest help.

**Closed by bmw** 2015-11-09 22:18 UTC
