### ISSUE TITLE
Stray "False False" in help output

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#1308] opened 2015-11-03 17:06 UTC
```
$ letsencrypt --server https://acme-v01.api.letsencrypt.org/directory --installer nginx --authenticator nginx --text --agree-eula -d 44.le-test.hoffman-andrews.com run -vvvv
False False
usage: 
  letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...
```

**Comment by TheNavigat** [comment] 2015-11-03 21:36
I know for a fact that this is caused by one of the recently merged PRs because I had to update my only 10 days old local repo to be able to reproduce this issue.

**Comment by kuba** [comment] 2015-11-03 21:46
There are a couple of debug statements in the code that should be removed:
- https://github.com/letsencrypt/letsencrypt/blob/b1508f38506376faabe753b343b93c7aeaa96121/letsencrypt/cli.py#L552
- https://github.com/letsencrypt/letsencrypt/blob/b1508f38506376faabe753b343b93c7aeaa96121/letsencrypt/cli.py#L560
- https://github.com/letsencrypt/letsencrypt/blob/b1508f38506376faabe753b343b93c7aeaa96121/letsencrypt/cli.py#L566
- https://github.com/letsencrypt/letsencrypt/blob/b1508f38506376faabe753b343b93c7aeaa96121/letsencrypt/cli.py#L938

**Comment by kuba** [comment] 2015-11-03 21:46
@TheNavigat, would you like to fix it?

**Comment by kuba** [comment] 2015-11-03 21:47
Also, https://github.com/letsencrypt/letsencrypt/blob/b1508f38506376faabe753b343b93c7aeaa96121/letsencrypt/cli.py#L658 should be changed to `sys.exit(usage)`

**Comment by TheNavigat** [comment] 2015-11-03 21:49
@kuba Yes, please. I've actually spent 15 minutes trying to understand why that happens, and the only progress I made was that it's probably in cli.py. It looks like I'll need way more time to understand how this works than I did with HTTPS Everywhere.

I'll create a pull request in a few.

**Comment by kuba** [comment] 2015-11-03 22:05
My comment about `sys.exit` was wrong: `sys.exit("string")` will trigger non-zero exit code, but for `--help` we should still return 0, sorry!

**Closed** 2015-11-03 22:43 UTC
