### ISSUE TITLE
Letsencrypt cannot deal with apache's WSGI configuration

### ISSUE THREAD

**Issue by ied206** [letsencrypt/letsencrypt#2546] opened 2016-02-25 04:26 UTC
Hello, I found current letsencrypt-auto has an issue with WSGIDaemonProcess config.

This is part of my apache2 config in _/etc/apache2/sites-enabled/003-ctf.conf_, which connects to django using WSGI.

```
WSGIDaemonProcess kctf python-path=/var/www/ctf:/var/www/ctf/kctfenv/lib/python2.7/site-packages
WSGIProcessGroup kctf
WSGIScriptAlias / /var/www/ctf/kctf/wsgi.py
```

This config forms default http connection.
When letsencrypt is run, it copies .conf file to another .conf file, then add ssl configurations, then restarting apache2 instantly.
However, WSGIDaemonProcess cannot be duplicated in .conf files, so letsencrypt-auto faces reboot failure and fall back.

This is because WSGIDaemonProcess which has same group name must exist in 'one' file.
If it exists in http conf file, it must be not in https conf file.

Currently, before running letsencrypt-auto, I must comment WSGIDaemonProcess temporary.
After running letsencrypt-auto, I uncomment WSGIDaemonProcess in http conf file and restart once more.
This way, WSGIDaemonProcess is commented in https conf file, so apache2 do not suffer from restart failure.

I hope letsencrypt gets better by fixing this problem.

**Comment by bmw** [comment] 2016-02-25 18:40
dupe of #1820?

**Comment by pde** [comment] 2016-02-25 19:40
Yes, duplicate I think.

**Closed by pde** 2016-02-25 19:40 UTC
