### ISSUE TITLE
insecure file permission for private key

### ISSUE THREAD

**Issue by blackm** [letsencrypt/letsencrypt#1540] opened 2015-11-17 20:03 UTC
Using today's (30 minutes ago) git clone and running the following command:

./letsencrypt-auto certonly -a standalone -d MYDOMAIN --server https://acme-v01.api.letsencrypt.org/directory --agree-dev-preview

resulted in a private key with the following permissions:

-rw-r--r-- 1 root root 1704 Nov 17 20:55 privkey1.pem

Not sure if the top folder with root only read permission is sufficent....

Except from with: WoW!

**Comment by bmw** [comment] 2015-11-18 00:17
Closing as a duplicate of #1473.

**Closed by bmw** 2015-11-18 00:17 UTC
