### ISSUE TITLE
Should not stop the apache server

### ISSUE THREAD

**Issue by kroeckx** [letsencrypt/letsencrypt#1339] opened 2015-11-04 18:37 UTC
It seems that as part of running letsencrypt the apache server is stopped and started again.  I see no good reason to stop it.

**Comment by pde** [comment] 2015-11-04 19:43
Closing as a duplicate of #954.

**Closed by pde** 2015-11-04 19:43 UTC
Labels: apache, duplicate

**Comment by pde** [comment] 2015-11-04 19:44
btw @kroeckx I don't think anyone has volunteered to take that ticket.  It's a little tricky, because of the need to wait and test whether the reload has produced the desired results, but should be doable.
