### ISSUE TITLE
Let's Encrypt certificate expiration notice

### ISSUE THREAD

**Issue by Crazee** [letsencrypt/letsencrypt#2483] opened 2016-02-16 19:46 UTC
I've started to get junk mail starting with
```
Hello,

Your certificate (or certificates) for the names listed below will expire in 17 days (on 03 Mar 16 18:43 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.
```
The problem is that this is about a certificate I regularly replace by auto-renewing it.  I'm not using the 2.5 month old version anymore but the replacement.

You shouldn't nag us about certs that have been replaced and no longer in use.

**Comment by schoen** [comment] 2016-02-16 20:06
Hi,

This is not a client issue; it's a duplicate of letsencrypt/boulder#1346

I'll post on letsencrypt/boulder#1346 to remind people working on that of the priority. Sorry for the inappropriate e-mails.

**Closed by schoen** 2016-02-16 20:06 UTC

**Comment by Crazee** [comment] 2016-02-16 20:21
Ah, well "letsencrypt/letsencrypt" is the part we interface with.  And a github keyword search (for possible duplicates) doesn't look in the other repositories.
