### ISSUE TITLE
issues on CentOS 7 x64

### ISSUE THREAD

**Issue by rodmackenzie** [letsencrypt/letsencrypt#1849] opened 2015-12-09 22:39 UTC
I followed the install steps to get the client for github, then I got:
./letsencrypt-auto --apache -d opvdm.com
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --apache -d opvdm.com
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()

**Comment by joohoi** [comment] 2015-12-10 07:10
Apache plugin does not currently support CentOS in master branch, but if you are willing to test, I have done the work needed for CentOS, but the pull request is still in review (and will be for some time, it's scheduled for 2.0). 

You can pull and test out [joohoi/letsencrypt/tree/multios_apache](https://github.com/joohoi/letsencrypt/tree/multios_apache). 
But please note, this is considered experimental at this phase.

The pull request can be seen here #1811

**Comment by bmw** [comment] 2015-12-11 01:01
Closing as a dupe of #788.

**Closed by bmw** 2015-12-11 01:01 UTC
