### ISSUE TITLE
Debian 7 doesn't seem to work either.

### ISSUE THREAD

**Issue by dhuseby** [letsencrypt/letsencrypt#1199] opened 2015-10-29 20:52 UTC
Debian 7 only has Python 2.7.3 and when the venv gets set up that's what it uses.  PyOpenSSL doesn't work with that version and things fail.  I had to compile Python 2.7.10 from source to finally get it to work.  This is similar to issue #1078 in that the Python version is just too damn old.

**Comment by dhuseby** [comment] 2015-10-29 21:01
@swartzcr this is for you :)

**Comment by dhuseby** [comment] 2015-10-29 21:02
I should add that this is a stock Debian 7 install running the ./letsencrypt-auto script.

**Comment by kuba** [comment] 2015-10-29 21:09
Can you please paste full output of `./letsencrypt-auto -v` (with Python 2.7.3)?

**Comment by dhuseby** [comment] 2015-10-29 21:26
here's the failure:

```
2015-10-29 21:24:54,566:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/huseby/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1097, in main
    return args.func(args, config, plugins)
  File "/home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 473, in auth
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 295, in _auth_from_domains
    lineage = _treat_as_renewal(config, domains)
  File "/home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 215, in _treat_as_renewal
    config, domains)
  File "/home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 189, in _find_duplicative_certs
    candidate_names = set(candidate_lineage.names())
  File "/home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/storage.py", line 435, in names
    with open(target) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by dhuseby** [comment] 2015-10-29 21:27
here's the part of the log showing what's installed in the venv:

```
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt-apache in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: zope.interface in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: acme==0.0.0.dev20151024 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python2-pythondialog>=3.2.2rc1 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: PyOpenSSL in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: requests in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: setuptools in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: parsedatetime in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: configobj in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pytz in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: psutil>=2.1.0 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: six in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: cryptography>=0.7 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: zope.component in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: mock in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: ConfigArgParse in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pyrfc3339 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python-augeas in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt-apache)
Requirement already up-to-date: pyasn1 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: ndg-httpsclient in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: werkzeug in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: idna>=2.0 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: enum34 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: ipaddress in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: cffi>=1.1.0 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: zope.event in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from zope.component->letsencrypt)
Requirement already up-to-date: funcsigs in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pbr>=0.11 in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pycparser in /home/huseby/.local/share/letsencrypt/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
Running with virtualenv: sudo /home/huseby/.local/share/letsencrypt/bin/letsencrypt -v auth --server https://acme-v01.api.letsencrypt.org/directory
```

**Comment by kuba** [comment] 2015-10-29 21:29
Can you please paste entire log, and not parts of it? Thanks! Also, the logs that you attached don't suggest any problems with `pyOpenSSL`.

**Comment by kuba** [comment] 2015-10-29 21:34
Did you touch any files in `/etc/letsencrypt` or `/var/lib/letsencrypt`? If so, then you shouldn't: https://github.com/letsencrypt/letsencrypt/issues/1195.

**Comment by dhuseby** [comment] 2015-10-29 22:02
@kuba so i'm doing this in a console and the curses dialogs blow away any/all of the output from the script.  so i'm not sure how you expect me to gather the output.

also, i temporarily downgraded the python on the system from python 2.7.10 (compiled from source) to python 2.7.3 to try to re-create the error.

i'm not blocked at all.  i compiled python 2.7.10 from source an everything worked.  @swartzcr wanted me to file a bug.  i think i'll have to set up a vm with stock debian 7 to really get good output.

is there a command line switch to turn off the curses full screen dialogs and get clean output from the script?

**Comment by kuba** [comment] 2015-10-29 22:04
You can use `letsencrypt-auto --text` to get rid of the Dialog display.

**Comment by dhuseby** [comment] 2015-10-29 22:05
i'll try again when i get a vm set up.  maybe tomorrow, probably next week.

**Comment by kuba** [comment] 2015-10-29 22:08
Most likely, however, you edited files in `/etc/letsencrypt` as I mentioned above. Am I right or not?

**Comment by dhuseby** [comment] 2015-10-29 23:46
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

no

On 10/29/2015 03:08 PM, Jakub Warmuz wrote:
> Most likely, however, you edited files in |/etc/letsencrypt| as I 
> mentioned above. Am I right or not?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/letsencrypt/letsencrypt/issues/1199#issuecomment-1
52342128>.
>
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCAAGBQJWMq/aAAoJEJ7v31qiCP4g1KAQAJOo1ihc/SSYoPZ7mOQtfk0u
rWTcIOYLSZcN2V8843kO3qMN4F7dBQ2IXFO2aNhYCMuahdga57u618Ve8J964Wn6
cUsEx3cbq+HQfOQgM5AH6Nh9Bghzfxri0B6Aag2z1AGjBuT733Q06bXuHL8so24v
ARnu6l3zDSQIfS9Vm+rtNuCZjvS1iO93LDvwG6lpqyQegFyG37aip9OnK06zGlsU
MSlkz6gbEdc1TD7lDDVJLBLVO/1kt1DOjgdY+NUTwCQdeYT6+DKOVoNcV0x4DBw9
2htGZXhUbxBM2xTQ/dUPaVP336cYHYtXDClnQN0yH8IuNBqtVMygKii092dfb6eP
nX0dbHXrOoIIjrSTiU9P/ehk9OAQav/osD0nsK7Z5+LVnG9ZpzLeo+1tLpUCQmEj
Jf3EIwZ3pQsfpQuFxutFrCL+753N9ep7HG4JCNMBsv4bd267ln9VAFm2qpscbCLM
3rN5EWnuFsYKHY7yfZc+YRHMtXcP1wYl3l69eZ0lFHlhCUOJyd5NO1CeZTwytmkX
+qHizXB0k0vOhWhkVjmlvEALywTjbIT6g6VDiiuSP7nAPY231MyuIHRo8u646CTP
gcXlBWZ/eIW1rfyU5vziVsTBH4VqPdGUr8+8GMgGsFyuRq89axZ+IvH0X3vravtl
J5ys9/TzTUpBSWex3wEj
=0inc
-----END PGP SIGNATURE-----

**Comment by dhuseby** [comment] 2015-10-29 23:47
@kuba no, I didn't edit any files.

**Comment by kuba** [comment] 2015-11-07 09:21
Since we don't have much evidence here, I'll close it as duplicate of #1195.

**Closed by kuba** 2015-11-07 09:21 UTC
Labels: more-info
