### ISSUE TITLE
Webroot authentication fails when no domains are specified

### ISSUE THREAD

**Issue by Juma7C9** [letsencrypt/letsencrypt#1700] opened 2015-12-03 22:59 UTC
If no domains are specified in `cli.ini` or on commandline (e.g. when using a `--csr` option, as the two are mutually exclusive), the process fails with the error `PluginError: --webroot-path must be set`, even if the option is set in the configuration file or passed on commandline.

If a list of domains is passed instead of a `csr` file, or if `manual` auth is used instead of `webroot`, the process completes successfully.

This is the (uncommented and sanitized) config file I used:
##### cli.ini
```
rsa-key-size = 4096
server = https://acme-staging.api.letsencrypt.org/directory
email = address@example.com

authenticator = webroot
webroot-path = /var/www/html/default

csr = /etc/letsencrypt/csr.der
```

And this is the log file:
##### /var/log/letsencrypt/letsencrypt.log.4
```
2015-12-03 21:59:13,215:DEBUG:letsencrypt.cli:Root logging level set at -20
2015-12-03 21:59:13,215:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-12-03 21:59:13,215:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.0
2015-12-03 21:59:13,217:DEBUG:letsencrypt.cli:Arguments: ['--debug', '-vvvvv', '--text']
2015-12-03 21:59:13,218:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-12-03 21:59:13,218:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2015-12-03 21:59:13,229:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache): 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt_apache/configurator.py", line 142, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-12-03 21:59:13,230:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-12-03 21:59:13,238:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/letsencrypt/plugins/webroot.py", line 54, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-12-03 21:59:13,239:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-12-03 21:59:13,239:DEBUG:letsencrypt.cli:Selected authenticator None and installer None

```

**Comment by pde** [comment] 2015-12-03 23:33
This is a duplicate of #1668

**Closed by pde** 2015-12-03 23:33 UTC
