### ISSUE TITLE
Conf file not generated for WSGI subdomain

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [letsencrypt/letsencrypt#2755] opened 2016-04-04 00:14 UTC
I tried to enable https for all my sites' subdomains simultaneously via
```
./letsencrypt-auto --apache -d deentaylor.com -d luke.deentaylor.com -d api.deentaylor.com -d www.deentaylor.com
```
In my setup, www.deentaylor.com is an alias for [deentaylor.com](https://deentaylor.com), which redirects to `luke.deentaylor.com`, so that any of those 3 pages will resolve to `luke.deentaylor.com`. 

After running these commands, I can visit https://api.deentaylor.com, https://deentaylor.com (which redirects) and https://www.deentaylor.com (which also redirects). However, I cannot visit https://luke.deentaylor.com without getting a 404. (I can still visit the insecure `http` site, although I did specify for letsencrypt to force `https`)

The problem seems to be that separate `.conf` files were generated for all domains *except* luke.deentaylor.com. With `ls /etc/apache2/sites-available/`, I see a `luke.deentaylor.com.conf` but *not* a `luke.deentaylor.com-le-ssl.conf`, while I do see an `api.deentaylor.com-le-ssl.conf` as well as a similar file for the other domains besides `luke.deentaylor.com`.

Re-running the command, this time targeting the domain specifically with `./letsencrypt-auto --apache -d luke.deentaylor.com`, doesn't resolve the issue.

Note that https://www.ssllabs.com/ssltest/analyze.html?d=luke.deentaylor.com doesn't see an issue.

**Comment by bmw** [comment] 2016-04-06 00:29
It appears that `letsencrypt` obtained your certificate and correctly enabled TLS for https://luke.deentaylor.com, but broke the site in doing so. This is why SSL labs doesn't see an issue and you see a green lock next to the URL when visiting that URL (in most browsers). HTTPS is working, but Apache isn't serving the correct files.

If you search the configuration files in `/etc/apache2/sites-available`, you should find some with either `ServerName luke.deentaylor.com` or `ServerAlias luke.deentaylor.com`. If so, I would be interested in seeing a (redacted) version of these files.

**Comment by The-Penultimate-Defenestrator** [comment] 2016-04-06 00:32
The only file is `luke.deentaylor.com.conf`, which I already had. No new file was generated. I'll post a redacted version of the file when I get home in about half an hour.

**Comment by The-Penultimate-Defenestrator** [comment] 2016-04-06 00:50
I don't believe there is anything which I need to redact, so here's the file:
```
<VirtualHost *:80>
        ServerAdmin ldt@deentaylor.com
        ServerName luke.deentaylor.com
        ServerAlias www.luke.deentaylor.com
        WSGIScriptAlias /wikipedia/api /var/www/luke/wikipedia/api/api.wsgi
        WSGIScriptAlias /wikipedia-dev/api /var/www/luke/wikipedia/api/api.wsgi
        DocumentRoot /var/www/luke/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

The `WSGIScriptAlias`es point to a Flask server used in a personal project. I have two paths that point to the same `wsgi` application because I develop this project with both a primary and a dev channel.

**Comment by pde** [comment] 2016-04-06 21:16
Ah, it looks as though this is a duplicate of #1820, possibly with different symptoms?

**Comment by The-Penultimate-Defenestrator** [comment] 2016-04-06 21:17
Very possibly.

**Comment by pde** [comment] 2016-04-06 21:21
Okay, will close this one; the 1820 ticket is scheduled for our next milestone.

**Comment by pde** [comment] 2016-04-06 21:22
(Meanwhile, some folks have been working around this by commenting out WSGI directives, running the client, and then uncommenting; you can also use the `--webroot` plugin and install certs manually).

**Comment by The-Penultimate-Defenestrator** [comment] 2016-04-06 21:23
Great. Thanks for your help.

**Closed by pde** 2016-04-06 21:22 UTC
Labels: apache, bug, duplicate
