### ISSUE TITLE
No installers seem to be present and working on your system

### ISSUE THREAD

**Issue by abhishekdgeek** [letsencrypt/letsencrypt#1804] opened 2015-12-07 08:57 UTC
Hi Team,
Thanks for this great work. I am trying to install my first free certificate on an IP and here are the console logs:

```
git clone https://github.com/letsencrypt/letsencrypt
Cloning into 'letsencrypt'...
remote: Counting objects: 25288, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 25288 (delta 2), reused 0 (delta 0), pack-reused 25275
Receiving objects: 100% (25288/25288), 6.65 MiB | 3.02 MiB/s, done.
Resolving deltas: 100% (17714/17714), done.
Checking connectivity... done.
ubuntu@ip-172-31-30-160:~$ cd letsencrypt
ubuntu@ip-172-31-30-160:~/letsencrypt$ ./letsencrypt-auto
Bootstrapping dependencies for Debian-based OSes...
Ign http://us-west-2.ec2.archive.ubuntu.com trusty InRelease
Get:1 http://us-west-2.ec2.archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Hit http://us-west-2.ec2.archive.ubuntu.com trusty Release.gpg                 
Hit http://us-west-2.ec2.archive.ubuntu.com trusty Release                     
Get:2 http://us-west-2.ec2.archive.ubuntu.com trusty-updates/main Sources [247 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com trusty-updates/universe Sources [144 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages [664 kB]
Ign http://repo.mongodb.org trusty/mongodb-org/3.0 InRelease                   
Get:5 http://us-west-2.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages [328 kB]
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/main Translation-en 
Hit http://us-west-2.ec2.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/main Sources                
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/universe Sources            
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/main amd64 Packages         
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/universe amd64 Packages     
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/main Translation-en         
Hit http://us-west-2.ec2.archive.ubuntu.com trusty/universe Translation-en     
Ign http://us-west-2.ec2.archive.ubuntu.com trusty/main Translation-en_US      
Ign http://us-west-2.ec2.archive.ubuntu.com trusty/universe Translation-en_US  
Get:6 http://security.ubuntu.com trusty-security InRelease [64.4 kB]           
Hit http://repo.mongodb.org trusty/mongodb-org/3.0 Release.gpg                 
Hit http://repo.mongodb.org trusty/mongodb-org/3.0 Release                     
Hit http://repo.mongodb.org trusty/mongodb-org/3.0/multiverse amd64 Packages   
Ign http://repo.mongodb.org trusty/mongodb-org/3.0/multiverse Translation-en_US
Ign http://repo.mongodb.org trusty/mongodb-org/3.0/multiverse Translation-en   
Get:7 http://security.ubuntu.com trusty-security/main Sources [100 kB]         
Get:8 http://security.ubuntu.com trusty-security/universe Sources [31.9 kB]
Get:9 http://security.ubuntu.com trusty-security/main amd64 Packages [381 kB]
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [120 kB]
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Fetched 2,147 kB in 2s (949 kB/s)                  
Reading package lists... Done
E: No packages found
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version.
gcc set to manually installed.
python is already the newest version.
ca-certificates is already the newest version.
git is already the newest version.
The following extra packages will be installed:
  augeas-lenses libffi6 libpython-dev libpython2.7 libpython2.7-dev
  libpython2.7-minimal libpython2.7-stdlib libssl1.0.0 python-pkg-resources
  python-setuptools python2.7 python2.7-dev python2.7-minimal
Suggested packages:
  augeas-doc augeas-tools python-distribute python-distribute-doc
  python2.7-doc binfmt-support
Recommended packages:
  python-pip
The following NEW packages will be installed:
  augeas-lenses dialog libaugeas0 libffi-dev libpython-dev libpython2.7-dev
  python-dev python-setuptools python-virtualenv python2.7-dev
The following packages will be upgraded:
  libffi6 libpython2.7 libpython2.7-minimal libpython2.7-stdlib libssl-dev
  libssl1.0.0 python-pkg-resources python2.7 python2.7-minimal
9 upgraded, 10 newly installed, 0 to remove and 160 not upgraded.
Need to get 31.3 MB of archives.
After this operation, 40.3 MB of additional disk space will be used.
Get:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libffi6 amd64 3.1~rc1+r3.0.13-12ubuntu0.1 [17.5 kB]
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libssl-dev amd64 1.0.1f-1ubuntu2.15 [1,073 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libssl1.0.0 amd64 1.0.1f-1ubuntu2.15 [826 kB]
Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main python2.7 amd64 2.7.6-8ubuntu0.2 [196 kB]
Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main python2.7-minimal amd64 2.7.6-8ubuntu0.2 [1,185 kB]
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libpython2.7 amd64 2.7.6-8ubuntu0.2 [1,039 kB]
Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libpython2.7-stdlib amd64 2.7.6-8ubuntu0.2 [1,869 kB]
Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libpython2.7-minimal amd64 2.7.6-8ubuntu0.2 [308 kB]
Get:9 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libpython2.7-dev amd64 2.7.6-8ubuntu0.2 [22.0 MB]
Get:10 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main augeas-lenses all 1.2.0-0ubuntu1.1 [230 kB]
Get:11 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/main dialog amd64 1.2-20130928-1 [300 kB]
Get:12 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libaugeas0 amd64 1.2.0-0ubuntu1.1 [135 kB]
Get:13 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/main libpython-dev amd64 2.7.5-5ubuntu3 [7,078 B]
Get:14 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main python2.7-dev amd64 2.7.6-8ubuntu0.2 [269 kB]
Get:15 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/main python-dev amd64 2.7.5-5ubuntu3 [1,166 B]
Get:16 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main python-pkg-resources all 3.3-1ubuntu2 [61.9 kB]
Get:17 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main python-setuptools all 3.3-1ubuntu2 [230 kB]
Get:18 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/universe python-virtualenv all 1.11.4-1 [1,485 kB]
Get:19 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main libffi-dev amd64 3.1~rc1+r3.0.13-12ubuntu0.1 [99.8 kB]
Fetched 31.3 MB in 0s (40.5 MB/s)  
Preconfiguring packages ...
(Reading database ... 60831 files and directories currently installed.)
Preparing to unpack .../libffi6_3.1~rc1+r3.0.13-12ubuntu0.1_amd64.deb ...
Unpacking libffi6:amd64 (3.1~rc1+r3.0.13-12ubuntu0.1) over (3.1~rc1+r3.0.13-12) ...
Preparing to unpack .../libssl-dev_1.0.1f-1ubuntu2.15_amd64.deb ...
Unpacking libssl-dev:amd64 (1.0.1f-1ubuntu2.15) over (1.0.1f-1ubuntu2.12) ...
Preparing to unpack .../libssl1.0.0_1.0.1f-1ubuntu2.15_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.1f-1ubuntu2.15) over (1.0.1f-1ubuntu2.12) ...
Preparing to unpack .../python2.7_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking python2.7 (2.7.6-8ubuntu0.2) over (2.7.6-8) ...
Preparing to unpack .../python2.7-minimal_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking python2.7-minimal (2.7.6-8ubuntu0.2) over (2.7.6-8) ...
Preparing to unpack .../libpython2.7_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking libpython2.7:amd64 (2.7.6-8ubuntu0.2) over (2.7.6-8) ...
Preparing to unpack .../libpython2.7-stdlib_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking libpython2.7-stdlib:amd64 (2.7.6-8ubuntu0.2) over (2.7.6-8) ...
Preparing to unpack .../libpython2.7-minimal_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking libpython2.7-minimal:amd64 (2.7.6-8ubuntu0.2) over (2.7.6-8) ...
Selecting previously unselected package libpython2.7-dev:amd64.
Preparing to unpack .../libpython2.7-dev_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking libpython2.7-dev:amd64 (2.7.6-8ubuntu0.2) ...
Selecting previously unselected package augeas-lenses.
Preparing to unpack .../augeas-lenses_1.2.0-0ubuntu1.1_all.deb ...
Unpacking augeas-lenses (1.2.0-0ubuntu1.1) ...
Selecting previously unselected package dialog.
Preparing to unpack .../dialog_1.2-20130928-1_amd64.deb ...
Unpacking dialog (1.2-20130928-1) ...
Selecting previously unselected package libaugeas0.
Preparing to unpack .../libaugeas0_1.2.0-0ubuntu1.1_amd64.deb ...
Unpacking libaugeas0 (1.2.0-0ubuntu1.1) ...
Selecting previously unselected package libpython-dev:amd64.
Preparing to unpack .../libpython-dev_2.7.5-5ubuntu3_amd64.deb ...
Unpacking libpython-dev:amd64 (2.7.5-5ubuntu3) ...
Selecting previously unselected package python2.7-dev.
Preparing to unpack .../python2.7-dev_2.7.6-8ubuntu0.2_amd64.deb ...
Unpacking python2.7-dev (2.7.6-8ubuntu0.2) ...
Selecting previously unselected package python-dev.
Preparing to unpack .../python-dev_2.7.5-5ubuntu3_amd64.deb ...
Unpacking python-dev (2.7.5-5ubuntu3) ...
Preparing to unpack .../python-pkg-resources_3.3-1ubuntu2_all.deb ...
Unpacking python-pkg-resources (3.3-1ubuntu2) over (3.3-1ubuntu1) ...
Selecting previously unselected package python-setuptools.
Preparing to unpack .../python-setuptools_3.3-1ubuntu2_all.deb ...
Unpacking python-setuptools (3.3-1ubuntu2) ...
Selecting previously unselected package python-virtualenv.
Preparing to unpack .../python-virtualenv_1.11.4-1_all.deb ...
Unpacking python-virtualenv (1.11.4-1) ...
Selecting previously unselected package libffi-dev:amd64.
Preparing to unpack .../libffi-dev_3.1~rc1+r3.0.13-12ubuntu0.1_amd64.deb ...
Unpacking libffi-dev:amd64 (3.1~rc1+r3.0.13-12ubuntu0.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Setting up libffi6:amd64 (3.1~rc1+r3.0.13-12ubuntu0.1) ...
Setting up libssl1.0.0:amd64 (1.0.1f-1ubuntu2.15) ...
Setting up libssl-dev:amd64 (1.0.1f-1ubuntu2.15) ...
Setting up libpython2.7-minimal:amd64 (2.7.6-8ubuntu0.2) ...
Setting up python2.7-minimal (2.7.6-8ubuntu0.2) ...
Setting up libpython2.7-stdlib:amd64 (2.7.6-8ubuntu0.2) ...
Setting up python2.7 (2.7.6-8ubuntu0.2) ...
Setting up libpython2.7:amd64 (2.7.6-8ubuntu0.2) ...
Setting up libpython2.7-dev:amd64 (2.7.6-8ubuntu0.2) ...
Setting up augeas-lenses (1.2.0-0ubuntu1.1) ...
Setting up dialog (1.2-20130928-1) ...
Setting up libaugeas0 (1.2.0-0ubuntu1.1) ...
Setting up libpython-dev:amd64 (2.7.5-5ubuntu3) ...
Setting up python2.7-dev (2.7.6-8ubuntu0.2) ...
Setting up python-dev (2.7.5-5ubuntu3) ...
Setting up python-pkg-resources (3.3-1ubuntu2) ...
Setting up python-setuptools (3.3-1ubuntu2) ...
Setting up python-virtualenv (1.11.4-1) ...
Setting up libffi-dev:amd64 (3.1~rc1+r3.0.13-12ubuntu0.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Creating virtual environment...
Updating letsencrypt and virtual environment dependencies...../home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
./home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
.
Running with virtualenv: sudo /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt
No installers seem to be present and working on your system; fix that or try running letsencrypt with the "certonly" command
```

Please tell me how to proceed. I am on AWS EC2 with ubuntu and nginx serving my node app as a proxy.

**Comment by bmw** [comment] 2015-12-10 23:32
Dupe of #1576.

**Closed by bmw** 2015-12-10 23:32 UTC
