### ISSUE TITLE
Request new cert failed

### ISSUE THREAD

**Issue by FabianCernota** [letsencrypt/letsencrypt#2597] opened 2016-03-03 20:35 UTC
```
2016-03-03 20:32:44,209:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-03-03 20:32:48,109:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-cert HTTP/1.1" 500 88
2016-03-03 20:32:48,114:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '88', 'Expires': 'Thu, 03 Mar 2016 20:32:48 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Mar 2016 20:32:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'DsfbYUV-WhPbvd0ab1LTZfsHULiAndN6cEWrNjJWfXs'}. Content: '{"type":"urn:acme:error:serverInternal","detail":"Error creating new cert","status":500}'
2016-03-03 20:32:48,115:DEBUG:acme.client:Storing nonce: '\x0e\xc7\xdbaE~Z\x13\xdb\xbd\xdd\x1aoR\xd3e\xfb\x07P\xb8\x80\x9d\xd3zpE\xab62V}{'
2016-03-03 20:32:48,115:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '88', 'Expires': 'Thu, 03 Mar 2016 20:32:48 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 03 Mar 2016 20:32:48 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'DsfbYUV-WhPbvd0ab1LTZfsHULiAndN6cEWrNjJWfXs'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new cert","status":500}'
2016-03-03 20:32:48,117:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 706, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 457, in _auth_from_domains
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 252, in obtain_certificate
    return self.obtain_certificate_from_csr(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_certificate_from_csr
    authzr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 319, in request_issuance
    headers={'Accept': content_type})
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 652, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 568, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new cert
```

Thanks,
Fabian

**Comment by bmw** [comment] 2016-03-03 23:20
@FabianCernota, have you tried running the client again? Do you consistently get this problem or was it a one time thing?

**Comment by muhlba91** [comment] 2016-03-04 12:28
same problem here - even after many tries

**Comment by FabianCernota** [comment] 2016-03-04 13:23
Tried it like 3 times or so. Not working

**Comment by benedopulus** [comment] 2016-03-04 14:44
I have this problem too:

`File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_certificate_from_csr authzr) File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 319, in request_issuance headers={'Accept': content_type}) File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 652, in post return self._check_response(response, content_type=content_type) File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 568, in _check_response raise messages.Error.from_json(jobj) Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new cert
`

**Comment by zivester** [comment] 2016-03-04 17:29
Also seeing this issue.  I have added some new domains but they are setup exactly as the others.  Added a combination of CNAME's / A Records if that is relevant.

I tried twice (spaced about an hour apart) and receive the same error.  Would rather not try again because of the retry limit.  The challenges seem to work just fine as it's only at the end of the run that everything fails.  Happy to provide any information/logs, although they are identical to this request.

**Comment by BrainStone** [comment] 2016-03-06 15:01
I have the same problem.

**Comment by schoen** [comment] 2016-03-07 22:21
Hi folks,

Thank you for reporting this problem. I've talked to colleagues on the CA side and they say that they've understood the reason for the problem and are in the process of fixing it. We apologize for the inconvenience.

If you get this error, your cert likely *was* issued successfully, and if you're familiar with manually configuring certs on your system, you can likely go get a copy from https://crt.sh/ by searching for your domain name. That copy, if it exists at all, should work properly when installed on your system. (However, if you do this for an initial install of the cert, you won't be able to use our tools for renewal later.)

**Comment by schoen** [comment] 2016-03-07 22:21
I'm going to close this issue because it was discovered to be a server-side issue (so it doesn't belong in this issue tracker, which is for client problems).

**Closed by schoen** 2016-03-07 22:21 UTC
Labels: boulder, bug, more-info

**Comment by BrainStone** [comment] 2016-03-07 22:37
@schoen And what about the people that are not familiar with manually configuring certs on their system? (Like me)

(If this is the wrong place to ask I apologize. But I don't know where else it would be fitting to ask this.)

**Comment by zivester** [comment] 2016-03-07 22:38
@schoen is there a public bug ticket that we can follow for progress of the upstream issue?

**Comment by schoen** [comment] 2016-03-07 22:56
@BrainStone, unfortunately you should probably wait for the CA bug to be fixed.

**Comment by schoen** [comment] 2016-03-07 22:58
@zivester, we may be able to get some information onto https://letsencrypt.status.io/ soon (it's not there yet).

You can also watch or comment at

https://community.letsencrypt.org/t/server-500-but-certificate-still-issued/11855/

The community forum is a more appropriate place than here because problems with the CA functionality are relevant there, whereas this particular GitHub repository is intended for client software development.

Thanks.

**Comment by schoen** [comment] 2016-03-07 22:59
My colleagues said they're hoping for a fix sometime today (March 7).

**Comment by advance512** [comment] 2016-12-19 22:16
FYI - this can happen with emails on invalid domains. (I wrote an erroneous domain name in the inputted email address and got this "internal server error" issue).

**Comment by cpu** [comment] 2016-12-19 22:17
@advance512 You got an "Internal server error" due to [this incident](https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/58585781770129780f000661). It will **not** be caused by an email with an invalid domain.

**Comment by advance512** [comment] 2016-12-19 23:54
Ah. I see. :)

Just a matter of luck then - it failed with the bad email (error 500), however when I deleted the previous account files and set a new email - it worked. Guess it was just lucky timing.

**Comment by fiery-** [comment] 2016-12-27 15:54
The same serverInternal 500 error on the last stage of cert renewal happened on: 'Mon, 26 Dec 2016 16:59:21 GMT'. Actually all certs which received this error appeared on [https://crt.sh/](url) after some time. The test with "--dry-run" completed successfully. Finally, creating a new cert (by removing the "/etc/letsencrypt" folder) worked without problems (certbot version: 0.9.3).

For those in the same position. If your receive 500 "Error creating new cert", just wait (10 min. to 1 hour) and check  [https://crt.sh/](url). If your cert is there, you can download the crt file from there. Your private key is in "/etc/letsencrypt/keys/" on your machine.

[https://letsencrypt.status.io/](url) now shows a degraded state on the same date, but in a different time window: from December 26, 2016 8:03PM UTC to December 26, 2016 9:57PM UTC

**Comment by littleBro** [comment] 2018-04-02 02:50
Hi guys, I experience the same thing now: "The server experienced an internal error :: Error creating new cert:". Is there any problems on your servers?

**Comment by byoungb** [comment] 2018-04-02 03:07
Yeah I am getting the same thing too. And since you are seeing it to maybe there is something wrong with their servers. Though this is my first time renewing this particular certificate. So I may have something misconfigured.
