### ISSUE TITLE
Several code paths (conf files, interactive domains, --csr) do not set webroot_map entries correctly

### ISSUE THREAD

**Issue by tobbez** [letsencrypt/letsencrypt#1668] opened 2015-12-02 21:51 UTC
This may or may not be intended.

If you set `webroot-path` in your config and don't specify your domains, letsencrypt fails with the following error:
```
The webroot plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('--webroot-path must be set',)
```
This is pretty confusing, both because `webroot-path` is set, and also because the code in question actually uses `webroot-map`, which is autogenerated in cli.py if both webroot and domains are specified upon invocation.

Previously this use pattern worked.

These changes were introduced in e1f0fcc and ffe6226e.

**Comment by pde** [comment] 2015-12-02 23:01
This sounds like a bug.  Perhaps when webroot-path is set via the config file, [WebrootPathProcessor](https://github.com/letsencrypt/letsencrypt/pull/1594/files#diff-54b2f468d57ef7436008bd031bc89711R1065) isn't called?  Or when the fields come from the config file, some of the ordering assumptions that underpin [these changes](https://github.com/letsencrypt/letsencrypt/pull/1594/files) might be violated?

In the mean time, you can set `webroot-map` in your config file.  It has to look like this IIRC:
```
webroot-map = {"domain.com,www.domain.com" : "/var/www/domain", "eg.is" : "/var/www/is"}
```
Unfortunately, you can't have newlines in there ATM because ConfigArgParse can't cope with them.  For now domains must be specified in addition to webroot-map, though in the future the latter may imply the former.

**Comment by tobbez** [comment] 2015-12-03 04:00
`WebrootPathProcessor` is called. However, if you haven't specified any domains before `webroot-path` (either in the config file or on the command line), the `WebrootPathProcessor` won't do anything, since `config.domains` is empty.

Later, when the `prepare` method of Authenticator (in [letsencrypt/plugins/webroot.py](https://github.com/letsencrypt/letsencrypt/blob/a191daf3eedcabc175a2de71abb0d29989a5c343/letsencrypt/plugins/webroot.py#L49)) is called, it only uses `webroot-map`, which is still empty since it was never populated.

**Comment by pde** [comment] 2015-12-03 10:35
@tobbez want to send us a PR?  That will let us land a fix more quickly :)

**Comment by tobbez** [comment] 2015-12-03 12:57
I'm just not sure what the right way to fix it is.

You could call `display_ops.choose_names` if `config.domains` is empty in `WebrootPathProcessor`, but this might lead to confusing/inconsistent behaviour if the `webroot- path` is specified before domains.

It could also be possible to use `HelpfulArgumentParser.prescan_for_flag` (or something similar) from `prepare_and_parse_args` and depending on the result show domain selection, before `HelpfulArgumentParser.parse_args` is called.

Or maybe do something logically equivalent in the `HelpfulArgumentParser` constructor (i.e. inject interactively selected domains into self.args if not present).

**Comment by PatrickHeppler** [comment] 2015-12-04 12:59
Another issue, for me, is that you can't use --webroot-path together with --csr because --domains and --csr are mutually exclusive

I would use both because I want to use my own CSR for HPKP and webroot to avoid downtime.

**Comment by karolyi** [comment] 2016-01-05 21:52
+1, I'd like to have this fixed, my certs will expire in early February, and because of this, I can't renew them.

**Comment by JonLundy** [comment] 2016-01-06 18:02
@karolyi i have had success using the [acme-tiny](https://github.com/diafygi/acme-tiny) client for doing renewals.

**Comment by lauri-elevant** [comment] 2016-01-06 18:05
+1 for https://github.com/diafygi/acme-tiny
It is quite close to what the LE client was supposed to be, IMHO.

**Comment by lope** [comment] 2016-01-09 08:32
I'm not sure if I'm having the same problem... but basically if I do
`letsencrypt-auto certonly --email foo@bar.com --webroot -w /path/to/webroot -d bar.com -d www.bar.com`
that works
but if I make a config file: `my.conf`
```
email = foo@bar.com
webroot-map = {"bar.com,www.bar.com" : "/path/to/webroot" }
```
and run it like so `letsencrypt-auto certonly --config /path/to/my.conf`
I get the interactive shell window asking me how I want to authenticate...

**Comment by iameli** [comment] 2016-01-15 07:04
Hmm. I'm not using a config file, but I guess `--domains` and `--csr` are mutually exclusive?

**Comment by filipochnik** [comment] 2016-01-21 06:10
Seems like the correct syntax in this example would be
`webroot-map = {"bar.com": "/path/to/webroot", "www.bar.com": "/path/to/webroot"}`.
This doesn't fix the bug though. It is caused by not adding the parsed domains to `config.domains`. I'll submit a PR fixing that.

**Comment by lope** [comment] 2016-01-21 06:29
@filipochnik That's not very terse syntax you wrote now :/ The commandline provides a more terse syntax already
--webroot -w /path/to/webroot -d bar.com -d www.bar.com

when adding a lot of domains and paving
/very/long/paths/where/the/webroots/are/and/rewriting/them/for/every/single/domain/can/get/verbose

:)

**Comment by filipochnik** [comment] 2016-01-21 06:34
I agree 100%, I'm just saying that's how it works and used to work :) Supporting the syntax in the way you wrote it would be indeed much nicer.

**Comment by K-os** [comment] 2016-02-04 15:46
This problem persists for me with revision 533ede4: I still see  `PluginError('--webroot-path must be set',)`, when using `--webroot` together with the `--csr`-option.
This is my commandline:
`letsencrypt certonly --webroot --webroot-path /var/www/letsencrypt --text --csr ~/tmpfs/smtpd.req`

**Comment by karolyi** [comment] 2016-02-05 11:56
+1

**Comment by bmw** [comment] 2016-02-05 19:11
Can confirm `--webroot-path` doesn't work with `--csr`.

**Comment by pde** [comment] 2016-02-06 21:50
OK, #2393 should in theory address these issues with --csr, though I haven't had a chance to manually test it yet...

**Comment by K-os** [comment] 2016-02-08 12:04
I'm sorry to say, #2393 does not seem to fix the problem for my. I just did `git merge remotes/origin/webroot-map-and-flags` and the problem persists, but with a different error message:

`The error was: PluginError('Missing parts of webroot configuration; please set either --webroot-path and --domains, or --webroot-map. Run with  --help webroot for examples.',)`

**Comment by pde** [comment] 2016-02-09 01:25
@K-os I saw your comment right after merging.  You're right, #2393 is buggy...

**Comment by pde** [comment] 2016-02-09 07:17
And now it's fixed, tested, and merged again.

**Closed by pde** 2016-02-09 07:17 UTC
Labels: has pr, renewal, Urgent, webroot

**Comment by K-os** [comment] 2016-02-09 10:29
Cool Thank's! I'll give it a try.

**Comment by K-os** [comment] 2016-02-09 10:36
It's fixed :-)
