### ISSUE TITLE
'auth' installs a config file

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#844] opened 2015-09-27 20:01 UTC
Steps to reproduce:

1. Have a domain `lastbart.at` configured in Apache for HTTP but not HTTPS.

`letsencrypt  --text --agree-eula --agree-tos -d lastbart.at -a apache auth`

Actual result:

File `/etc/apache2/sites-available/lastbart.at-le-ssl.conf` is created, has two lines pointing at non-existent files:

SSLCertificateFile insert_cert_file_path
SSLCertificateKeyFile insert_key_file_path

Expected result:

No config files are left behind after successful authentication.

**Comment by jdkasten** [comment] 2015-09-27 20:12
Thanks! Duplicate of https://github.com/letsencrypt/letsencrypt/issues/808

**Closed** 2015-09-27 23:38 UTC
