### ISSUE TITLE
Don't make privatekey world readable

### ISSUE THREAD

**Issue by spaceone** [letsencrypt/letsencrypt#1757] opened 2015-12-04 23:13 UTC
The private key is currently created with o+r (others+read) permissions. The protection is done by removing the executable flag from the directory. Please set an explicit umask when (auto)creating the privatekey.

**Comment by spaceone** [comment] 2015-12-04 23:19
I am allowing multiple users on my server to have their letsencrypt certificates by 
```
chmod +x /etc/letsencrypt/archive/;
chgrp myuser /etc/letsencrypt/archive/my.user.net;
chmod 0770 /etc/letsencrypt/archive/my.user.net
```

**Comment by schoen** [comment] 2015-12-04 23:38
Thanks for the report. This is a duplicate of issue #1473.

**Closed by schoen** 2015-12-04 23:38 UTC
