### ISSUE TITLE
Failing on email address

### ISSUE THREAD

**Issue by brianmorton** [letsencrypt/letsencrypt#2725] opened 2016-03-29 02:02 UTC
First time user, so it could definitely be my fault, but I read the docs briefly and ran
```
 root@host:$ ./letsencrypt-auto --apache -d wzy.ca --email address@gmail.com --agree-tos
```

Which gave me back:
```
    Checking for new version...
    Requesting root privileges to run letsencrypt...
       /root/.local/share/letsencrypt/bin/letsencrypt --apache -d wzy.ca --email address@gmail.com --agree-tos
    An unexpected error occurred:
    The provided email for a registration was invalid :: DNS problem: query timed out looking up MX for gmail.com
```

This is on Debian 8.3 Jessie running on a Seattle based VPS.

If I'm doing something wrong or need to provide more info, please let me know!

**Comment by whithajess** [comment] 2016-03-29 02:47
I think there is some kind of DNS resolution problem on the lets encrypt servers, I get the same MX failure and then when I try with `--register-unsafely-without-email` I get the same deal `DNS problem: query timed out looking up A for HOST`

**Comment by whithajess** [comment] 2016-03-29 02:51
Literally just re-ran the command and it worked, guess someone fixed it.

**Comment by pde** [comment] 2016-03-31 23:26
Closing this for now, please reopen if you encounter this again.

**Closed by pde** 2016-03-31 23:26 UTC
Labels: boulder

**Comment by edgr-sanchez** [comment] 2016-04-06 06:54
I just tried to run ./letsencrypt-auto and it gave me the same exact error.

**Comment by sean-bennett112** [comment] 2016-04-06 18:58
Also been seeing this for about the past 12-13 hours. Though adding `--register-unsafely-without-email` did resolve the issue, rather then leading to another `DNS problem`.

**Comment by zinovyev** [comment] 2016-11-09 02:13
I've just got the same problem. The issue occures when I'm trying to run certbot with iptables service enabled. Does it uses any other ports rather than 443, 80, 53?

**Comment by cpu** [comment] 2016-11-09 14:54
Hi folks :wave:, leaving a comment here for any future wayward souls that discover this thread.

We recently changed the at-registration-time email validation in Boulder, the Let's Encrypt server-side CA, to [treat DNS lookups as best-effort](https://github.com/letsencrypt/boulder/pull/2288) rather than failing on timeout. I suspect this will start alleviating the symptom folks in this thread are experiencing. 

The root cause lies not with Certbot or Boulder and is indicative of (one or more of) your authoritative DNS servers responding slowly for the MX and A/AAAA lookups done to try and validate the email address.

If folks continue to run into this they should open an [issue on the Boulder repo](https://github.com/letsencrypt/boulder/issues/) so we can help troubleshoot there. Please include your domain/email address (we can of-course discuss alternate communication methods if you're unhappy sharing email/domains in Github tickets).

Thanks!
