### ISSUE TITLE
Only require user to agree to user agreement once

### ISSUE THREAD

**Issue by paulschreiber** [letsencrypt/letsencrypt#1365] opened 2015-11-05 02:43 UTC
Only require users to agree to user agreement once.

Do not require the user to agree every run, either by selecting "Yes" in the UI or by passing `--agree-dev-preview` as argument.

**Comment by pde** [comment] 2015-11-05 03:32
I believe this is a duplicate of #887.

One of these things is a warning about the client being experimental (and not getting valid certs by default).  The other is an actual agreement with the CA

**Closed by pde** 2015-11-05 03:32 UTC
Labels: duplicate

**Comment by bmw** [comment] 2015-11-05 20:18
While not exactly a dupe, this annoyance with `--agree-dev-preview` is only temporary and will be fixed with #887. Once we've launched, you won't need to agree to this developer preview at all.
