### ISSUE TITLE
Private keys are world readable (!)

### ISSUE THREAD

**Issue by kousu** [letsencrypt/letsencrypt#1792] opened 2015-12-06 14:32 UTC
```
root@comms:/etc/letsencrypt/archive/comms.kousu.ca# ls -l
total 32
-rw-r--r-- 1 root root 1793 Dec  6 05:27 cert1.pem
-rw-r--r-- 1 root root 1809 Dec  6 06:06 cert2.pem
-rw-r--r-- 1 root root 1675 Dec  6 05:27 chain1.pem
-rw-r--r-- 1 root root 1675 Dec  6 06:06 chain2.pem
-rw-r--r-- 1 root root 3468 Dec  6 05:27 fullchain1.pem
-rw-r--r-- 1 root root 3484 Dec  6 06:06 fullchain2.pem
-rw-r--r-- 1 root root 1704 Dec  6 05:27 privkey1.pem  <--- what???
-rw-r--r-- 1 root root 1704 Dec  6 06:06 privkey2.pem  <--- no, really, what?
```

These files are protected because `letsencrypt` made a higher folder -x:
``` 
root@comms:/etc/letsencrypt/archive/comms.kousu.ca# ls -ld /etc/letsencrypt/live/
drwx------ 3 root root 4096 Dec  6 05:27 /etc/letsencrypt/live/
root@comms:/etc/letsencrypt/archive/comms.kousu.ca# ls -ld /etc/letsencrypt/archive/
drwx------ 3 root root 4096 Dec  6 05:27 /etc/letsencrypt/archive/
```
But it would be good practice to -x the files themselves, just in case.

**Comment by pde** [comment] 2015-12-06 17:47
Duplicate of: #1473

**Closed by pde** 2015-12-06 17:47 UTC
