### ISSUE TITLE
Private keys created with world-readable permissions!?

### ISSUE THREAD

**Issue by shelvacu** [letsencrypt/letsencrypt#1821] opened 2015-12-08 01:37 UTC
I just ran `letsencrypt-auto` with the standalone module, and everything worked fine except that the private key file was created with world-readable permissions (-rw-r--r-- or 0644)

Any private keys should never be created with world-readable permissions.

**Comment by schoen** [comment] 2015-12-08 01:39
Thanks for the report. This is a duplicate of #1473.

**Closed by schoen** 2015-12-08 01:39 UTC
