### ISSUE TITLE
letsencrypt-auto   -> silent mode

### ISSUE THREAD

**Issue by pexus** [letsencrypt/letsencrypt#2126] opened 2016-01-09 06:08 UTC
I tried to install a certificate using the command 

letsencrypt-auto --apache  --email x@abc.com --text --agree-tos --rsa-key-size 4096 -d domain.name 

I still see it is waiting for input. Is there a completely silent option ? I did not see any option to completely suppress any interaction. I am looking to write script that will be called from a web application, which means I would need a silent option that just returns an error and not wait for any user input.  I checked the --help all, did not find any option. Any pointer is highly appreciated or suggest if this feature can be included.  Thanks in advance.

**Comment by lope** [comment] 2016-01-09 08:55
+1 I would also like some kind of -y --yes --force option.

For example I had a domain with bar.com and www.bar.com
now I added mail.bar.com and it tried to interact with me and ask if I want mail.bar.com added to my certificate. I would like a FORCE option to just say Yes yes yes. Even if my server blows up into tiny pieces, JUST DO IT!

**Comment by pde** [comment] 2016-01-09 22:58
This is a duplicate of #804, which is scheduled for 0.3.0.

**Closed** 2016-01-09 22:59 UTC
Labels: duplicate, has pr
