### ISSUE TITLE
letsencrypt-auto fails with no working sudo

### ISSUE THREAD

**Issue by adamhorner** [letsencrypt/letsencrypt#1447] opened 2015-11-10 13:41 UTC
This is possible on gentoo, maybe others.
PR to come with a simple error message and quit when no working sudo found

**Comment by tedb** [comment] 2015-11-10 15:07
I would prefer if letsencrypt-auto does not run sudo itself.  I should have to run the utility as sudo myself if it needs root permissions.

**Comment by bmw** [comment] 2015-11-10 20:25
Closing as a dupe of #1148.

**Closed by bmw** 2015-11-10 20:25 UTC
