### ISSUE TITLE
command line help needs to match command line design

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#285] opened 2015-03-17 01:45 UTC
Over in [this issue](https://github.com/letsencrypt/lets-encrypt-preview/issues/136) we have a design for the major verbs and different subcategories of options that the client needs to expose in order to be as swiftly comprehensible as possible to users.

Currently the client, if invoked with --help, prints this:

```
usage: letsencrypt [-h] [-d DOMAIN [DOMAIN ...]] [-s SERVER] [-k AUTHKEY]
                   [-B N] [-R] [--revoke-certificate REV_CERT]
                   [--revoke-key REV_KEY] [-b N] [-v] [-r] [--no-confirm] [-e]
                   [-t] [--config-dir CONFIG_DIR] [--work-dir WORK_DIR]
                   [--backup-dir BACKUP_DIR] [--key-dir KEY_DIR]
                   [--cert-dir CERT_DIR] [--le-vhost-ext LE_VHOST_EXT]
                   [--cert-path CERT_PATH] [--chain-path CHAIN_PATH]
                   [--apache-server-root APACHE_SERVER_ROOT]
                   [--apache-mod-ssl-conf APACHE_MOD_SSL_CONF]
                   [--apache-ctl APACHE_CTL] [--apache-enmod APACHE_ENMOD]
                   [--apache-init-script APACHE_INIT_SCRIPT]
                   [-c FILE [FILE ...]] [--export-conf-file [FILE]]
```
followed by a very long and seemingly randomly-ordered list of options.

It should list the major command verbs at the top, with [options] for each one, not an exhaustive list.  Then enumerate the most important options, and save the subcategories of options for if the user runs with <tt>-h -h</tt>, or asks for help about options for a specific verb.

**Comment by pde** [comment] 2015-03-17 01:46
Happy to provide a mockup of what this should look like if more clarity is needed : )

**Comment by jdkasten** [comment] 2015-03-17 05:31
I think we should remove the top "usage" printout and leave only the detailed descriptions.  The "usage section" is useless, but since this is autogenerated by ConfArgParse, I haven't looked into whether or not this is easily achieved.

I personally haven't spent any time organizing the list yet, though I think it can be greatly improved with [sections] (https://pypi.python.org/pypi/ConfArgParse/1.0.15).

There is also some cleanup/refactoring required for cert-path/cert-dir and key-path/key-dir. (Cert/Key named output). (These options were poorly transferred back from when we had a CONFIG.py file.)

**Comment by kuba** [comment] 2015-05-02 09:04
I'm working on that in https://github.com/kuba/lets-encrypt-preview/tree/cli

This looks like a duplicate of #136. Can we close one?

**Closed** 2015-10-20 03:09 UTC
Labels: ui / ux
