### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/letsencrypt#136] opened 2014-12-18 02:10 UTC
![command-line](https://cloud.githubusercontent.com/assets/1581662/5482522/dde0a4aa-8617-11e4-830e-814fcc473392.jpg)

Potential changes to command line

**Comment by ThomasWaldmann** [comment] 2015-01-23 04:26
do you really want to have 1 separate script command per supported software (letsencrypt-apache, letsencrypt-nginx, ...)?

how about: letsencrypt apache --getcert/--revoke/...

**Comment by kuba** [comment] 2015-05-02 09:04
I'm working on that in https://github.com/kuba/lets-encrypt-preview/tree/cli

This looks like a duplicate of #285. Can we close one?

**Comment by pde** [comment] 2015-05-15 19:09
@saschaf is considering doing some user studies with a mockup of this ...

**Comment by bmw** [comment] 2015-09-25 20:42
Closing as picture is largely outdated.

**Closed by bmw** 2015-09-25 20:42 UTC
Labels: enhancement, ui / ux
