### ISSUE TITLE
Mac OS X Server "/.well-known/acme-challenge/***KEY***" 

### ISSUE THREAD

**Issue by mooretechman** [letsencrypt/letsencrypt#2710] opened 2016-03-24 18:40 UTC
I know that this is how letsencrypt verifies that I own the server, however when I make the required file for this URL and navigate to it this is what OS X Server produces:

> Websites are turned off.
> An administrator can turn them on using the Server application.

Does anybody know how I can fix this issue?

**Comment by nitmir** [comment] 2016-03-25 11:17
duplicate of #1782

**Comment by pde** [comment] 2016-04-06 22:16
Closing as a duplicate.

**Closed by pde** 2016-04-06 22:16 UTC
Labels: duplicate, os x
