### ISSUE TITLE
Support "http-01" ACME challenge

### ISSUE THREAD

**Issue by bifurcation** [letsencrypt/letsencrypt#1166] opened 2015-10-28 01:01 UTC
The existing "simpleHttp" and "dvsni" challenges are insecure, and boulder will be disabling them shortly.  The client needs to implement the new "http-01" challenge in order to be compatible with future boulder.

**Comment by bifurcation** [comment] 2015-10-28 01:01
Propose adding this to the launch milestone.

**Comment by bmw** [comment] 2015-10-28 01:17
Dupe of #914 which is a launch milestone.

**Closed by bmw** 2015-10-28 01:17 UTC
