### ISSUE TITLE
Self-verify failure - New Line Char Issue - Can we strip/trim string before compare?

### ISSUE THREAD

**Issue by mitnk** [letsencrypt/letsencrypt#1329] opened 2015-11-04 14:40 UTC
Hello LE team,

When we write a string into a file to let say nginx to host. The editor say vim will usually append an `\n` char at then end of file. This is such a common issue, that could we make the compare more friendly to trim the string?

See the following log to see more information.

```
[2015-11-04 14:31:01,259][DEBUG] Verifying http-01 at http://www.mydomain.com/.well-known/acme-challenge/vzmN2NoPYrcKyNIfHBS6tZAVwqppvlwGtOYKHRhM-Ek...
[2015-11-04 14:31:01,265][INFO] Starting new HTTP connection (1): www.mydomain.com
[2015-11-04 14:31:01,623][DEBUG] "GET /.well-known/acme-challenge/vzmN2NoPYrcKyNIfHBS6tZAVwqppvlwGtOYKHRhM-Ek HTTP/1.1" 200 None
[2015-11-04 14:31:01,626][DEBUG] Received <Response [200]>: vzmN2NoPYrcKyNIfHBS6tZAVwqppvlwGtOYKHRhM-Ek.B3wfZ_czp3_9e5lz8fZ0ASl8lbgUrmQg2I5stz3lYaM
. Headers: {'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Server': 'nginx/1.9.5', 'Last-Modified': 'Wed, 04 Nov 2015 14:30:56 GMT', 'Connection': 'keep-alive', 'ETag': 'W/"563a16a0-58"', 'Date': 'Wed, 04 Nov 2015 14:31:01 GMT', 'Content-Type': 'text/plain'}
[2015-11-04 14:31:01,628][DEBUG] Key authorization from response 
(u'vzmN2NoPYrcKyNIfHBS6tZAVwqppvlwGtOYKHRhM-Ek.B3wfZ_czp3_9e5lz8fZ0ASl8lbgUrmQg2I5stz3lYaM') doesn't match HTTP response 
(u'vzmN2NoPYrcKyNIfHBS6tZAVwqppvlwGtOYKHRhM-Ek.B3wfZ_czp3_9e5lz8fZ0ASl8lbgUrmQg2I5stz3lYaM\n')
[2015-11-04 14:31:01,628][ERROR] Self-verify of challenge failed, authorization abandoned.
```

**Comment by kuba** [comment] 2015-11-04 20:03
Duplicate of #1322.

**Closed by kuba** 2015-11-04 20:03 UTC
Labels: acme, duplicate
