### ISSUE TITLE
letsencrypt-renewer does not work with letsencrypt 0.3.0

### ISSUE THREAD

**Issue by weberhofer** [letsencrypt/letsencrypt#2420] opened 2016-02-10 16:10 UTC
```bash
# letsencrypt-renewer 
Processing somehost.mydomain.eu.conf
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "/usr/bin/letsencrypt-renewer", line 9, in <module>
    load_entry_point('letsencrypt==0.3.0', 'console_scripts', 'letsencrypt-renewer')()
  File "/usr/lib/python2.7/site-packages/letsencrypt/renewer.py", line 203, in main
    renew(cert, old_version)
  File "/usr/lib/python2.7/site-packages/letsencrypt/renewer.py", line 97, in renew
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(sans)
  File "/usr/lib/python2.7/site-packages/letsencrypt/client.py", line 264, in obtain_certificate
    csr = crypto_util.init_save_csr(key, domains, self.config.csr_dir)
  File "/usr/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 78, in init_save_csr
    csr_pem, csr_der = make_csr(privkey.pem, names)
  File "/usr/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 118, in make_csr
    value=", ".join("DNS:%s" % d for d in domains)
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 651, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a str or list or tuple, not unicode

**Comment by schoen** [comment] 2016-02-10 20:15
(Duplicate of #2360.)

`letsencrypt-renew` is being replaced imminently with `letsencrypt renew`; please see

https://community.letsencrypt.org/t/help-us-test-renewal-with-letsencrypt-renew/10562

I apologize for the inconvenience.

**Closed** 2016-02-10 20:15 UTC

**Comment by weberhofer** [comment] 2016-02-11 16:24
Works nicely with version 0.4.0. Thanks!
