### ISSUE TITLE
"Client does not support any combination of challenges that will satisfy the CA"

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1302] opened 2015-11-03 06:51 UTC
https://travis-ci.org/letsencrypt/boulder/jobs/88704098

For

```
2015-11-02 00:06:46,690:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '719', 'Link': '<http://127.0.0.1:4000/acme/new-cert>;rel="next"', 'Location': 'http://127.0.0.1:4000/acme/authz/yPOuQU388P8oFUxLKMJ092jRrS3Q4-UWrwhefnfeiH0', 'Date': 'Mon, 02 Nov 2015 00:06:46 GMT', 'Content-Type': 'application/json', 'Replay-Nonce': 'idscPvxITjVxROZRhVm6ovrF9hq2FR5qrKut3bzftn4'}): '{"identifier":{"type":"dns","value":"le1.wtf"},"status":"pending","expires":"2015-11-09T00:06:46.655707728Z","challenges":[{"type":"simpleHttp","status":"pending","uri":"http://127.0.0.1:4000/acme/challenge/yPOuQU388P8oFUxLKMJ092jRrS3Q4-UWrwhefnfeiH0/4","token":"6IatTwbE56MgGKiwpuc8ErcCndSIRLodeeDE5onkGyA","tls":true},{"type":"http-01","status":"pending","uri":"http://127.0.0.1:4000/acme/challenge/yPOuQU388P8oFUxLKMJ092jRrS3Q4-UWrwhefnfeiH0/5","token":"QbvQkufEOyApGWPnxm37TIdQouylZu7Q0W5FmnjONsA"},{"type":"tls-sni-01","status":"pending","uri":"http://127.0.0.1:4000/acme/challenge/yPOuQU388P8oFUxLKMJ092jRrS3Q4-UWrwhefnfeiH0/6","token":"_ymVZSuTDEr9QSZHX15USwJLLf4c8bbSZWZoxnbLQPI"}],"combinations":[[0],[1],[2]]}'
```

we seem to be throwing `AuthorizationError: Client does not support any combination of challenges that will satisfy the CA.`

cc @bifurcation

**Comment by bifurcation** [comment] 2015-11-03 07:40
If you look through that the sequence of Travis runs in that PR, you can see that I tried offering the following sets of challenges (in each case, indicating that any one of the three would be sufficient):

* `simpleHttp, http-01, tls-sni-01`
* `dvsni, http-01, tls-sni-01`
* `simpleHttp, dvsni, http-01, tls-sni-01`

Only the last one worked.  That smells to me like the client expects to see both challenges.

**Comment by kuba** [comment] 2015-11-03 08:01
The error I pointed out corresponds to
```
2015-11-02 00:06:46,211:DEBUG:letsencrypt.cli:Arguments: ['--server', 'http://localhost:4000/directory', '--no-verify-ssl', '--dvsni-port', '5001', '--simple-http-port', '5002', '--manual-test-mode', '--config-dir', '/tmp/leitPsLA/conf', '--work-dir', '/tmp/leitPsLA/work', '--logs-dir', '/tmp/leitPsLA/logs', '--text', '--no-redirect', '--agree-dev-preview', '--agree-tos', '--email', '', '--renew-by-default', '--debug', '-vvvvvvv', '--authenticator', 'standalone', '--installer', 'null', '--domains', 'le1.wtf', '--standalone-supported-challenges', 'dvsni']
```
so it was expected to fail if it couldn't find `dvsni` (`---standalone-supported-challenges dvsni`).

**Comment by kuba** [comment] 2015-11-03 08:09
It's the same for https://travis-ci.org/letsencrypt/boulder/jobs/88638699, but that one failed when we demanded `--standalone-supported-challenges simpleHttp`, and you only offered `dvsni`, `http-01`, `tls-sni-01`:

```
2015-11-01 14:33:27,727:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '703', 'Link': '<http://127.0.0.1:4000/acme/new-cert>;rel="next"', 'Location': 'http://127.0.0.1:4000/acme/authz/jbesJzIM1eJ9HCj7LJ3YcRqvLajdZ-U8YJbbCVrrLok', 'Date': 'Sun, 01 Nov 2015 14:33:27 GMT', 'Content-Type': 'application/json', 'Replay-Nonce': '5A54aFituo0mwj1fLwR2KR0TJQVGzMfYavjcwmm7wNw'}): '{"identifier":{"type":"dns","value":"le2.wtf"},"status":"pending","expires":"2015-11-08T14:33:26.971375621Z","challenges":[{"type":"dvsni","status":"pending","uri":"http://127.0.0.1:4000/acme/challenge/jbesJzIM1eJ9HCj7LJ3YcRqvLajdZ-U8YJbbCVrrLok/7","token":"LpcCA9_Seq-WUqdv5nzpArS4HbOEn1450rOGt4qpSNI"},{"type":"http-01","status":"pending","uri":"http://127.0.0.1:4000/acme/challenge/jbesJzIM1eJ9HCj7LJ3YcRqvLajdZ-U8YJbbCVrrLok/8","token":"VVsIUl4HZImN7u6lVtez9xCYUub0dhvE1SYq4q_mZQw"},{"type":"tls-sni-01","status":"pending","uri":"http://127.0.0.1:4000/acme/challenge/jbesJzIM1eJ9HCj7LJ3YcRqvLajdZ-U8YJbbCVrrLok/9","token":"Uhw7tkpx0nCd7WFrbCSTgnjLzYX2irr_rR2bVp4Yef8"}],"combinations":[[0],[1],[2]]}'
```

So, everything is working as inteded: our integration tests are properly catching, that Boulder didn't offer excepted (single) challenge. You can see what's happening on the integration tests side over here: https://github.com/letsencrypt/letsencrypt/blob/master/tests/boulder-integration.sh.

**Comment by bifurcation** [comment] 2015-11-03 08:24
To elaborate on what @kuba said, the issue is in the boulder integration tests -- they configure the client to require `simpleHttps` and `dvsni` exclusively, in separate tests.  So if one of those two is not enabled, the respective test will fail.

**Comment by bifurcation** [comment] 2015-11-03 08:31
Correction: It's the client's integration test that sets the required challenge types.

So it seems to me that there are two bugs here:
1. The client integration tests should not fail if the server does not offer a challenge
2. The server integration tests should explicitly run the client, not blindly accept what the client does.

I could probably be convinced that (1) is not exactly the right way to go, but we should fix (2).

**Comment by kuba** [comment] 2015-11-03 18:01
1. Client integration tests **should** fail if the server does not offer the challenge. If Boulder has an error which forbids it from serving a challenge, how would we detect it? How else should we test that the implementation of all challenges in client and server is OK? In fact, I'm very happy to have tests that detect breaking change on Boulder side, such as in this case! You should not pull in your breaking PRs until client is ready (you can track progress at #914). Once the changes land in `master`, integration tests will pass.
2. Please open a ticket on https://github.com/letsencrypt/boulder?

Due to above can you please close this ticket?

**Comment by bmw** [comment] 2015-11-04 22:33
Since it seems clear to me that the problem this issue was created for has been resolved, I'm closing this ticket. If the client cannot perform any challenge provided by the server, the client cannot proceed and needs to exit. In normal use cases, this is an error. I'm sorry you had trouble with testing your PR.

**Closed by bmw** 2015-11-04 22:33 UTC
