### ISSUE TITLE
Can't issue for long names

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#2881] opened 2016-04-21 21:12 UTC
Steps to reproduce:

```
letsencrypt certonly --test-cert -d ba3b3d43d3ae11881adf64a63780716b49055a32.le-test.hoffman-andrews.com --standalone
An unexpected error occurred:
Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]
Please see the logfiles in /var/log/letsencrypt for more details.
```

Here's the full stack plus a few lines of context from the log:

```
2016-04-21 21:13:33,671:INFO:letsencrypt.auth_handler:Cleaning up challenges
2016-04-21 21:13:33,671:DEBUG:letsencrypt.plugins.standalone:Stopping server at 0.0.0.0:443...
2016-04-21 21:13:34,008:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/2337_key-letsencrypt.pem
2016-04-21 21:13:34,009:DEBUG:letsencrypt.main:Exiting abnormally:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 692, in main
    return config.func(config, plugins)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 509, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 93, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 274, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 254, in obtain_certificate
    csr = crypto_util.init_save_csr(key, domains, self.config.csr_dir)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 78, in init_save_csr
    csr_pem, csr_der = make_csr(privkey.pem, names)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 111, in make_csr
    req.get_subject().CN = domains[0]
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 495, in __setattr__
    _raise_current_error()
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too long')]
```

I'm guessing the problem is that the client tries to encode the long name into CN, which is not allowed. When a long name is provided, the client should put it in a SAN and leave the CN blank.

**Comment by bmw** [comment] 2016-04-21 21:17
Dupe of #1915

**Closed by bmw** 2016-04-21 21:17 UTC
