### ISSUE TITLE
letsencrypt-auto generated mixed IPv6 and IPv4 vhost apache config line

### ISSUE THREAD

**Issue by nils-ohlmeier** [letsencrypt/letsencrypt#1349] opened 2015-11-04 22:48 UTC
The virtual host config for the Apache I tried to get a certificate for looks like this:

`<VirtualHost [2a01:238:429e:6b00:6188:46:8080:e1b4]:80 85.214.41.172:80>`

letsencrypt-auto generate a apache config file with the following vhost:

`<VirtualHost [2a01:443 85.214.41.172:443>`

**Comment by nils-ohlmeier** [comment] 2015-11-04 23:08
Probably the same issue as issue 1143

**Comment by kroeckx** [comment] 2015-11-04 23:09
So this is just really the same issue as #1143, but with IPv6 address before IPv4 address and then it makes "[2XXX" the IPv4 address.

**Comment by bmw** [comment] 2015-11-04 23:19
Thanks for the report @nils-ohlmeier. I agree that this is a dupe of #1143 but I very much appreciate you taking the time to report the issue.

**Closed by bmw** 2015-11-04 23:19 UTC
Labels: duplicate
