### ISSUE TITLE
Installation failed (crash) due to missing expected symlink

### ISSUE THREAD

**Issue by paulschreiber** [letsencrypt/letsencrypt#2064] opened 2016-01-02 14:39 UTC
```
# /usr/local/letsencrypt/letsencrypt-auto --apache certonly -d paulschreiber.com
Updating letsencrypt and virtual environment dependencies......
Requesting root privileges to run with virtualenv: /home/paul/.local/share/letsencrypt/bin/letsencrypt --apache certonly -d paulschreiber.com
An unexpected error occurred:
TypeError: coercing to Unicode: need string or buffer, NoneType found
Please see the logfiles in /var/log/letsencrypt for more details.
```

Here's the log:
```
2016-01-02 14:37:21,067:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-01-02 14:37:21,069:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-01-02 14:37:21,074:DEBUG:letsencrypt.cli:letsencrypt version: 0.1.1
2016-01-02 14:37:21,074:DEBUG:letsencrypt.cli:Arguments: ['--apache', '-d', 'paulschreiber.com']
2016-01-02 14:37:21,075:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-01-02 14:37:21,086:DEBUG:letsencrypt.cli:Requested authenticator apache and installer apache
2016-01-02 14:37:23,104:DEBUG:letsencrypt.display.ops:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fba08835e50>
Prep: True
2016-01-02 14:37:23,107:DEBUG:letsencrypt.display.ops:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fba08835e50>
Prep: True
2016-01-02 14:37:23,107:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fba08835e50> and installer <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fba08835e50>
2016-01-02 14:37:23,137:DEBUG:letsencrypt.cli:Picked account: <Account(21cf43e4b9e154c6234364199d89e025)>
2016-01-02 14:37:23,139:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-01-02 14:37:23,145:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-01-02 14:37:23,415:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2016-01-02 14:37:23,420:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Sat, 02 Jan 2016 14:37:23 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sat, 02 Jan 2016 14:37:23 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'SOuHmwjWdG9q34ITRxS7Y_jGjA9HHusxwBarijt9W5Q'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-01-02 14:37:23,421:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Sat, 02 Jan 2016 14:37:23 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sat, 02 Jan 2016 14:37:23 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'SOuHmwjWdG9q34ITRxS7Y_jGjA9HHusxwBarijt9W5Q'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-01-02 14:37:23,426:DEBUG:letsencrypt.storage:Expected symlink /etc/letsencrypt/live/paulschreiber.com-0001/cert.pem for cert does not exist.
2016-01-02 14:37:23,480:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/paul/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
    return args.func(args, config, plugins)
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 598, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 379, in _auth_from_domains
    action, lineage = _treat_as_renewal(config, domains)
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 235, in _treat_as_renewal
    ident_names_cert, subset_names_cert = _find_duplicative_certs(config, domains)
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 204, in _find_duplicative_certs
    candidate_names = set(candidate_lineage.names())
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 459, in names
    with open(target) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

The directory `/etc/letsencrypt/live/paulschreiber.com-0001` no longer exists.

**Comment by paulschreiber** [comment] 2016-01-02 14:53
I removed the files from `/etc/letsencrypt/live/` and was able to reinstall the cert as needed.

**Comment by pde** [comment] 2016-01-05 20:08
In theory `/etc/letsencrypt/live` is supposed to only contain symlinks to the real certs (so they can be updated to always have the latest cert, without removing the history of what existed beforehand, which is kept in `/etc/letsencrypt/archive`).  Do you know how you managed to have that not be the case?

**Comment by paulschreiber** [comment] 2016-01-07 03:32
I had a cert I wanted reissued, and there were two copies of it from various beta versions. I deleted files from `/etc/letsencrypt/archive`, ran it, and got the error. I then deleted files from `/etc/letsencrypt/live/` and the problem went away. (I also deleted the corresponding files from `/etc/letsencrypt/renewal` — not sure if that was during step 1 or step 2.)

**Comment by bmw** [comment] 2016-01-12 01:12
Closing as a duplicate of #1195.

**Closed by bmw** 2016-01-12 01:12 UTC
