### ISSUE TITLE
client v0.4.2 completes successfully but outputs error at the end

### ISSUE THREAD

**Issue by fsantiago07044** [letsencrypt/letsencrypt#2611] opened 2016-03-05 18:34 UTC
This was on centos 7.2.x.

I ran the LE client v0.4.2 with following CLI options:

./letsencrypt-auto certonly -a webroot --webroot-path <my path> -c /etc/letsencrypt/cli.ini -d <my domain> 

my cli.ini contains:

server = https://acme-v01.api.letsencrypt.org/directory
renew-by-default
agree-tos
noninteractive
email = <my email>

after obtaining a cert just now, it congratulated me with the standard finishing output dialog and i received my cert and all seemed normal except it outputted at the very end the following line:

./letsencrypt-auto: line 1810: tag: command not found

just a heads up. need anything else from me?

**Comment by bmw** [comment] 2016-03-07 21:51
@fsantiago07044, does this happen consistently or did it only happen once?

**Comment by fsantiago07044** [comment] 2016-03-08 00:36
I've only seen it once so far but will check. Standby. 

Sincerely,

Fabian Santiago

**Comment by fsantiago07044** [comment] 2016-03-08 04:26
well, i'm trying again, and with two different domain's renewal attempts, i now receive this:

Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt certonly -a webroot --webroot-path /usr/share/cacti -c /etc/letsencrypt/cli.ini -d cacti.garbage-juice.com
An unexpected error occurred:
ClientError: <Response [503]>
Please see the logfiles in /var/log/letsencrypt for more details.


LE log data can be found here:   http://pastebin.com/X1DCpLQj

so now what's up?

**Comment by bmw** [comment] 2016-03-08 20:19
@jsha: Above is a log of 500s from https://acme-v01.api.letsencrypt.org/directory. Any idea what could be the cause?

**Comment by jsha** [comment] 2016-03-09 00:11
Thanks for flagging this. Our server logs do show an increase in 503s recently. We are investigating to see why, and will fix.

**Comment by lorenzos** [comment] 2016-03-09 07:54
Same here. Ubuntu 14.04.4 LTS here, on Sun, 06 Mar 2016 03:47:30 +0000 during scheduled renewal (weekly cron) I got:

```
Checking for new version...
Upgrading letsencrypt-auto 0.4.0 to 0.4.2...
Replacing letsencrypt-auto...
   cp /tmp/tmp.d66JrpJgkx/letsencrypt-auto /home/ubuntu/letsencrypt/letsencrypt-auto
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --no-self-upgrade renew
Processing /etc/letsencrypt/renewal/xxxxxxxxxxx.conf

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/xxxxxxxxxxx/fullchain.pem (skipped)
No renewals were attempted.
/home/ubuntu/letsencrypt/letsencrypt-auto: 1810: /home/ubuntu/letsencrypt/letsencrypt-auto: tag: not found
```

Retrying now shows no errors, no updates:

```
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt renew
Processing /etc/letsencrypt/renewal/xxxxxxxxxxx.conf

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/xxxxxxxxxxx/fullchain.pem (skipped)
No renewals were attempted.
```

**Comment by jsha** [comment] 2016-03-09 16:54
@fsantiago07044: regarding the errors you got in http://pastebin.com/X1DCpLQj, they should be resolved. We had a config problem at our CDN causing an elevated number of 500s.

**Comment by fsantiago07044** [comment] 2016-03-09 18:56
confirmed; works fine and weird error msg at end is also gone.

**Comment by bmw** [comment] 2016-03-09 19:04
Great! I'm glad the problem was resolved.

I'm closing this issue due to it being a symptom of #2456 on older `letsencrypt-auto` scripts.

**Closed by bmw** 2016-03-09 19:04 UTC
Labels: letsencrypt-auto, more-info
