### ISSUE TITLE
./letsencrypt-auto --help installs software WITHOUT asking!

### ISSUE THREAD

**Issue by TeGuy** [letsencrypt/letsencrypt#2698] opened 2016-03-22 10:58 UTC
Sorry, but are you insane?

I was just trying to test your software - and you are installing packages nad python environments without asking?

You should ALWAYS ask a user if you are allowed to install sw. ESPECIALLY if the user invokes only the "help" command!

Please give me a list of files and packages your software installed. I want to purge it completely!

**Comment by nitmir** [comment] 2016-03-22 14:47
Duplicate of #1903 (the main one) and #1286, #2229 and #2680 and possibly other ones…

**Comment by bmw** [comment] 2016-03-22 19:17
Yes, this is a duplicate and something that frustrates me personally as well. Closing, but I'll try to get this behavior changed here soon.

**Closed by bmw** 2016-03-22 19:17 UTC
