### ISSUE TITLE
Failure to detect webroot in CentOS7

### ISSUE THREAD

**Issue by NeilHanlon** [letsencrypt/letsencrypt#1094] opened 2015-10-23 17:27 UTC
In CentOS7 (and presumably other RPM/RHEL-based systems), the tool fails to detect the Apache installation on the system, which I believe to be due to it looking for the install at /etc/apache2, instead of the Cent/RHEL default of /etc/httpd.

The directory layout, for reference, on my Cent box is:

[root@drop3 ~]# find /etc/httpd/ -type d
/etc/httpd/
/etc/httpd/conf
/etc/httpd/conf.d
/etc/httpd/conf.modules.d

the conf folder holds httpd.conf (global).
conf.d holds vhost or module-specific configs
conf.modules.d holds LoadModule statements.

Kuba created #1092 as a byproduct of this w.r.t. a "bad" failure message here.

Happy to test any fixes, and I'm going to look into it myself, as well.

**Comment by kuba** [comment] 2015-10-23 17:29
I think at this stage we should just "fix" it in the docs (maybe provide example config file for RHEL?) and leave the rest to distro maintainers.

**Comment by bmw** [comment] 2015-10-23 18:10
Unfortunately, the problem is actually deeper than that. It's true that the Apache plugin expects your server root to be at `/etc/apache2`, but this can be set using the `--apache-server-root` option on the command line.

Currently, the Apache plugin only works on Debian based systems because it relies on Debian specific Apache executables such as `a2enmod`. We're working on the problem (see #788) but I wonder if this should be closed as a dupe of that issue?

**Comment by NeilHanlon** [comment] 2015-10-23 18:43
Perhaps a workaround in that case, would be to load whatever modules are necessary into /etc/httpd/conf.modules.d ?

Putting stuff in there does similar things to what a2enmod does. I've never liked how debian/ubuntu kinda butcher the config into so many files--but that's besides the point.

Just basically detecting whether a LoadModule line exists in any file inside /etc/httpd/conf.modules.d/ -- as this is best practice for CentOS7. Previous versions don't do this, so it'd really only work for 7.

**Comment by Larzenegger** [comment] 2015-10-24 12:47
To find the httpd configuration directory, a command like the following could be useful:
`httpd -D DUMP_RUN_CFG | grep 'ServerRoot:' | sed -r -e '{ s/.*\"(.*)\"/\1/ }' `

To locate the config file for a specific virtual host, similar parsing of `httpd -D DUMP_VHOSTS` might work.

_Used httpd instead of apachectl because fedora 22 no longer supports apachectl arguments other than start/stop/restart._

**Comment by jdkasten** [comment] 2015-10-29 20:05
As @bmw mentioned, multiple OS support hasn't been attempted for Apache yet.  The goal is to use the best practices for each distribution.  This will be addressed with #788.

Currently closing this as a duplicate.  Thanks!

**Closed by jdkasten** 2015-10-29 20:05 UTC
Labels: apache, duplicate, fedora / redhat / CentOS
