### ISSUE TITLE
Support multiple contact addresses

### ISSUE THREAD

**Issue by jsha** [letsencrypt/letsencrypt#975] opened 2015-10-14 17:53 UTC
The ACME protocol allows multiple contact addresses on a registration object. The client should allow specifying multiple addresses also. This is important if there are multiple people who need to be aware of certificate expiration events. See, for instance, https://community.letsencrypt.org/t/library-freedom-project-is-looking-for-people-who-can-help-libraries-with-https/1490.

**Comment by bmw** [comment] 2015-10-14 18:10
Dupe of #741

**Closed** 2015-10-14 18:19 UTC
